import type { MCQ, QuestionSet } from "../../types";

export const mcq: QuestionSet<MCQ> = {
  id: "mcq-inorganic",
  title: "Multiple choice · Inorganic Chemistry",
  subtitle: "Group 1, Group 7, air, the reactivity series, rusting and extracting metals",
  topic: "inorganic",
  questions: [
    // ───────── WARM-UP ─────────
    {
      id: "in-m01",
      topic: "inorganic",
      section: "inorganic-group1",
      difficulty: "warmup",
      question: "Which products are formed when sodium reacts with cold water?",
      options: [
        "sodium oxide and hydrogen",
        "sodium hydroxide and hydrogen",
        "sodium hydroxide and oxygen",
        "sodium oxide and water vapour",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Tempting because sodium tarnishes to an oxide in air, but with water the product is the hydroxide, NaOH.",
        "2Na + 2H₂O → 2NaOH + H₂ — every alkali metal gives a hydroxide and hydrogen with water.",
        "The hydroxide part is right, but the gas is hydrogen (it burns with a squeaky pop), not oxygen — the oxygen stays in the OH⁻ ion.",
        "Metal oxides form when metals burn in oxygen; with water the products are the hydroxide and hydrogen gas.",
      ],
      explanation:
        "Alkali metal + water → metal hydroxide + hydrogen. For sodium: 2Na(s) + 2H₂O(l) → 2NaOH(aq) + H₂(g). The sodium hydroxide dissolves to make an alkaline solution — which is why these are called the alkali metals.",
      hints: ["The name 'alkali metals' tells you what kind of solution forms — which compound makes water alkaline?"],
      strategy: "Recall the definition",
    },
    {
      id: "in-m02",
      topic: "inorganic",
      section: "inorganic-group7",
      difficulty: "warmup",
      question: "What is the colour and physical state of bromine at room temperature?",
      options: ["yellow-green gas", "grey-black solid", "red-brown liquid", "pale yellow gas"],
      answerIndex: 2,
      optionFeedback: [
        "This describes chlorine, the halogen above bromine.",
        "This describes iodine, the halogen below bromine.",
        "Bromine is the only non-metal element that is a liquid at room temperature — a dense red-brown liquid giving off orange-brown vapour.",
        "This describes fluorine, at the top of Group 7.",
      ],
      explanation:
        "Down Group 7 the molecules get bigger, intermolecular forces get stronger and the colour darkens: F₂ pale yellow gas, Cl₂ yellow-green gas, Br₂ red-brown liquid, I₂ grey-black solid. Bromine dissolved in water looks orange.",
      hints: ["Bromine sits between a gas (chlorine) and a solid (iodine) in the group."],
      strategy: "Recall the definition",
    },
    {
      id: "in-m03",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "warmup",
      question: "Approximately what percentage by volume of dry air is oxygen?",
      options: ["78%", "0.04%", "0.9%", "21%"],
      answerIndex: 3,
      optionFeedback: [
        "78% is nitrogen, the main gas in air.",
        "0.04% is carbon dioxide — a tiny fraction, though important for the greenhouse effect.",
        "0.9% (about 1%) is argon, the most common noble gas in air.",
        "Oxygen makes up about one fifth — 21% — of dry air.",
      ],
      explanation:
        "Dry air is about 78% nitrogen, 21% oxygen, 0.9% argon and 0.04% carbon dioxide by volume. The oxygen percentage is what you find experimentally by passing air over hot copper or using damp iron filings.",
      hints: ["Oxygen is roughly one fifth of air."],
      strategy: "Recall the definition",
    },
    {
      id: "in-m04",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "warmup",
      question: "Which metal does NOT react with dilute hydrochloric acid?",
      options: ["magnesium", "zinc", "copper", "iron"],
      answerIndex: 2,
      optionFeedback: [
        "Magnesium is high in the series and fizzes rapidly in dilute acid, making magnesium chloride and hydrogen.",
        "Zinc is above hydrogen, so it reacts steadily with dilute acid to give zinc chloride and hydrogen.",
        "Copper is below hydrogen in the reactivity series, so it cannot displace hydrogen from the acid.",
        "Iron is above hydrogen; it reacts slowly with dilute acid to form iron(II) chloride and hydrogen.",
      ],
      explanation:
        "Only metals above hydrogen in the reactivity series react with dilute acids to give a salt and hydrogen. Copper, silver and gold are below hydrogen, so there is no fizzing at all.",
      hints: ["Where does hydrogen sit in the reactivity series, and which metal is below it?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "in-m05",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "warmup",
      question: "Which statement defines oxidation in terms of electrons?",
      options: [
        "Oxidation is the loss of electrons.",
        "Oxidation is the gain of electrons.",
        "Oxidation is the gain of protons.",
        "Oxidation is the loss of oxygen.",
      ],
      answerIndex: 0,
      optionFeedback: [
        "OILRIG: Oxidation Is Loss of electrons.",
        "This is reduction — Reduction Is Gain of electrons.",
        "Redox is about electron transfer; protons in the nucleus do not change in chemical reactions.",
        "Loss of oxygen is reduction, and the question asks about electrons, not oxygen.",
      ],
      explanation:
        "In terms of electrons, oxidation is loss and reduction is gain (OILRIG). In terms of oxygen, oxidation is gain of oxygen and reduction is loss of oxygen. Both definitions always agree for the same reaction.",
      hints: ["Remember OILRIG."],
      strategy: "Recall the definition",
    },
    {
      id: "in-m06",
      topic: "inorganic",
      section: "inorganic-metals",
      difficulty: "warmup",
      question: "Which metal is extracted from its ore by electrolysis rather than by heating with carbon?",
      options: ["iron", "zinc", "copper", "aluminium"],
      answerIndex: 3,
      optionFeedback: [
        "Iron is below carbon in the reactivity series, so it is extracted in the blast furnace by reduction with carbon (monoxide).",
        "Zinc is below carbon, so its oxide can be reduced by heating with carbon.",
        "Copper is well below carbon and is easily reduced by carbon.",
        "Aluminium is above carbon in the reactivity series, so carbon cannot remove oxygen from aluminium oxide — electrolysis is needed.",
      ],
      explanation:
        "The extraction method depends on reactivity. Metals above carbon (K, Na, Ca, Mg, Al) are extracted by electrolysis of a molten compound; metals below carbon (Zn, Fe, Cu) can be reduced by heating with carbon, which is cheaper.",
      hints: ["Compare each metal's position with carbon in the reactivity series."],
      strategy: "Apply it to a new situation",
    },

    // ───────── CORE ─────────
    {
      id: "in-m07",
      topic: "inorganic",
      section: "inorganic-group1",
      difficulty: "core",
      question: "Which observation is seen when sodium is added to water but NOT when lithium is added to water?",
      options: [
        "The metal floats on the water.",
        "Bubbles of gas are given off.",
        "The metal melts into a ball.",
        "The solution turns universal indicator purple.",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Both lithium and sodium are less dense than water, so both float.",
        "Both metals fizz because both produce hydrogen.",
        "Sodium's reaction releases enough heat to melt it (melting point 98 °C); lithium reacts more slowly and has a higher melting point, so it stays solid.",
        "Both make an alkaline hydroxide solution (LiOH or NaOH), so universal indicator turns purple in both.",
      ],
      explanation:
        "Sodium melts into a silvery ball because the reaction is exothermic and fast enough to heat the metal above its low melting point (98 °C). Lithium reacts more gently and melts at 181 °C, so it fizzes steadily but stays solid.",
      hints: [
        "Cross out any observation caused by something both metals share (density, product gas, product solution).",
        "Which property of sodium is low enough that the heat of reaction can change its state?",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "in-m08",
      topic: "inorganic",
      section: "inorganic-group1",
      difficulty: "core",
      question: "Why is potassium more reactive than sodium?",
      options: [
        "Potassium has more electrons in its outer shell than sodium.",
        "Potassium's outer electron is further from the nucleus, so it is less strongly attracted.",
        "Potassium has a larger nuclear charge, so it attracts its outer electron more strongly.",
        "Potassium has a lower density than sodium, so it reacts faster.",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Both are in Group 1, so both have exactly one outer electron (Na 2,8,1; K 2,8,8,1).",
        "With an extra shell and more shielding, potassium's outer electron is held more weakly and is lost more easily.",
        "The nuclear charge is larger, but the extra shell and shielding outweigh it — the outer electron is held LESS strongly, which is why K is more reactive.",
        "Density does not explain reactivity; reactivity depends on how easily the outer electron is lost.",
      ],
      explanation:
        "Group 1 metals react by losing their single outer electron. Down the group the outer electron is further from the nucleus and more shielded by inner shells, so the attraction is weaker and the electron is lost more easily — reactivity increases.",
      hints: [
        "Write out the electronic configurations of Na and K. What is the same, and what is different?",
        "Think about distance from the nucleus and shielding by inner shells.",
      ],
      strategy: "Think about electrons",
    },
    {
      id: "in-m09",
      topic: "inorganic",
      section: "inorganic-group1",
      difficulty: "core",
      question: "Use the data in the table to predict the most likely melting point of caesium, the element below rubidium in Group 1.",
      table: {
        caption: "Melting points of Group 1 metals",
        headers: ["Element", "Melting point (°C)"],
        rows: [
          ["lithium", "181"],
          ["sodium", "98"],
          ["potassium", "63"],
          ["rubidium", "39"],
        ],
      },
      options: ["29 °C", "120 °C", "39 °C", "−40 °C"],
      answerIndex: 0,
      optionFeedback: [
        "Melting point falls down the group and the drops get smaller (83, 35, 24), so a drop of about 10 °C to roughly 29 °C fits the pattern (actual value 28.5 °C).",
        "This would mean the trend reverses — melting point decreases steadily down Group 1, so caesium must be lower than rubidium.",
        "This is rubidium's value; caesium should continue the downward trend.",
        "This over-extrapolates: the falls are getting smaller each time (83 → 35 → 24), so the next drop should be smaller than 24 °C, not 79 °C.",
      ],
      explanation:
        "Melting point decreases down Group 1 because the metal ions get larger, so the attraction between the ions and the delocalised electrons gets weaker. The differences shrink (83, 35, 24 °C), so the next drop is roughly 10 °C, giving about 29 °C — caesium would melt on a hot day.",
      hints: [
        "Is the melting point going up or down down the group?",
        "Work out the difference between each pair of values. Is that difference getting bigger or smaller?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "in-m10",
      topic: "inorganic",
      section: "inorganic-group7",
      difficulty: "core",
      question: "Chlorine water is added to colourless potassium iodide solution. What is seen?",
      options: [
        "The solution turns orange.",
        "The solution turns brown.",
        "A white precipitate forms.",
        "Purple fumes are given off.",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Orange is the colour of bromine in solution — you would see this if chlorine were added to a BROMIDE.",
        "Chlorine is more reactive than iodine, so it displaces iodine: Cl₂ + 2I⁻ → 2Cl⁻ + I₂, and iodine in aqueous solution is brown.",
        "No insoluble solid forms — potassium chloride is soluble. White precipitates belong to tests like silver nitrate with chloride ions.",
        "Purple vapour is seen when solid iodine is HEATED; at room temperature the iodine formed stays dissolved and looks brown.",
      ],
      explanation:
        "A more reactive halogen displaces a less reactive halogen from its halide: Cl₂(aq) + 2KI(aq) → 2KCl(aq) + I₂(aq). Iodine in water is brown. Learn the solution colours: bromine orange, iodine brown.",
      hints: [
        "Is chlorine more or less reactive than iodine?",
        "Which halogen is formed — and what colour is it when dissolved in water?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "in-m11",
      topic: "inorganic",
      section: "inorganic-group7",
      difficulty: "core",
      question: "Hydrogen chloride gas is dissolved in methylbenzene. Blue litmus paper is dipped into the solution. Which statement is correct?",
      options: [
        "litmus turns red because HCl ionises to form H⁺ ions",
        "litmus turns red because methylbenzene is acidic",
        "litmus bleaches because chlorine is released",
        "litmus stays blue because HCl does not ionise",
      ],
      answerIndex: 3,
      optionFeedback: [
        "This is what happens in WATER. In methylbenzene the HCl does not ionise, so there are no H⁺ ions.",
        "Methylbenzene is a neutral organic solvent, not an acid.",
        "Bleaching is the test for chlorine gas, Cl₂; hydrogen chloride does not release chlorine.",
        "In methylbenzene HCl stays as covalent molecules; with no H⁺ ions the solution is not acidic, so blue litmus stays blue.",
      ],
      explanation:
        "Acidity needs H⁺ ions. In water, HCl ionises: HCl(aq) → H⁺(aq) + Cl⁻(aq), so the solution is acidic. In methylbenzene the HCl stays as molecules, so there are no H⁺ ions and it does not behave as an acid.",
      hints: [
        "What particles must be present for a solution to be acidic?",
        "Does water play a part in releasing those particles from HCl?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "in-m12",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "core",
      question: "Copper(II) carbonate is heated strongly in a test tube. Which observation and product are correct?",
      options: [
        "green solid turns black; carbon dioxide given off",
        "black solid turns green; oxygen given off",
        "green solid turns white; carbon dioxide given off",
        "blue solid turns black; water vapour given off",
      ],
      answerIndex: 0,
      optionFeedback: [
        "CuCO₃(s) → CuO(s) + CO₂(g): green copper(II) carbonate becomes black copper(II) oxide, and the gas turns limewater milky.",
        "This is backwards — the black product is copper(II) oxide, and no oxygen gas is formed.",
        "The CO₂ is right, but copper(II) oxide is black, not white (white is typical of zinc or calcium oxide).",
        "Blue → white with water is hydrated copper(II) sulfate; copper carbonate is green and gives carbon dioxide.",
      ],
      explanation:
        "Thermal decomposition breaks a metal carbonate into a metal oxide and carbon dioxide: CuCO₃(s) → CuO(s) + CO₂(g). The colour change green → black is a favourite exam observation, and limewater turning milky confirms CO₂.",
      hints: [
        "Carbonate → oxide + which gas?",
        "What colour is copper(II) oxide?",
      ],
      strategy: "Recall the definition",
    },
    {
      id: "in-m13",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "core",
      question: "Magnesium and sulfur are each burned in oxygen. Each product is shaken with water containing universal indicator. Which row is correct?",
      table: {
        headers: ["", "Magnesium", "Sulfur"],
        rows: [
          ["A", "bright white flame; indicator turns blue", "blue flame; indicator turns red"],
          ["B", "bright white flame; indicator turns red", "blue flame; indicator turns blue"],
          ["C", "blue flame; indicator turns blue", "bright white flame; indicator turns red"],
          ["D", "bright white flame; indicator stays green", "blue flame; indicator stays green"],
        ],
      },
      options: ["A", "B", "C", "D"],
      answerIndex: 0,
      optionFeedback: [
        "Magnesium burns with a bright white flame to form MgO, a basic oxide (slightly alkaline); sulfur burns with a blue flame to form SO₂, an acidic oxide.",
        "The flames are right but the oxides are swapped — metal oxides are basic, non-metal oxides are acidic.",
        "The flame colours are swapped — magnesium's flame is the famous bright white one.",
        "Both oxides change the indicator: MgO is slightly alkaline and SO₂ dissolves to form an acidic solution.",
      ],
      explanation:
        "2Mg + O₂ → 2MgO (bright white flame, white powder) and S + O₂ → SO₂ (blue flame, pungent gas). Metal oxides are basic; non-metal oxides are acidic. That is why sulfur dioxide from fuels causes acid rain.",
      hints: [
        "Which element is a metal and which is a non-metal?",
        "Metal oxides are basic, non-metal oxides are acidic — now check the flame colours.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "in-m14",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "core",
      question: "60.0 cm³ of air is passed repeatedly over heated copper. After cooling to room temperature, 47.4 cm³ of gas remains. What is the percentage of oxygen in this sample of air?",
      options: ["79.0%", "12.6%", "21.0%", "26.6%"],
      answerIndex: 2,
      optionFeedback: [
        "This is the percentage of gas LEFT (47.4 ÷ 60.0 × 100), i.e. the nitrogen, argon etc., not the oxygen.",
        "This is the volume of oxygen in cm³ (60.0 − 47.4), not a percentage of the original volume.",
        "Oxygen used = 60.0 − 47.4 = 12.6 cm³; 12.6 ÷ 60.0 × 100 = 21.0%.",
        "This is what you get if you divide by the final volume (12.6 ÷ 47.4) instead of the original 60.0 cm³.",
      ],
      explanation:
        "The copper removes the oxygen (2Cu + O₂ → 2CuO), so the decrease in volume is the oxygen.\n- decrease = 60.0 − 47.4 = 12.6 cm³\n- % oxygen = 12.6 ÷ 60.0 × 100 = 21.0%\nAlways divide by the original volume of air.",
      hints: [
        "Which volume is the oxygen — the volume left, or the volume that disappeared?",
        "Percentage = part ÷ whole × 100. What is the 'whole' here?",
      ],
      strategy: "Follow the method step by step",
    },
    {
      id: "in-m15",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "core",
      question: "Which statement best explains how an increase in carbon dioxide in the atmosphere leads to global warming?",
      options: [
        "Carbon dioxide destroys the ozone layer, so more heat from the Sun reaches the Earth.",
        "Carbon dioxide absorbs infrared radiation emitted by the Earth's surface, so less heat escapes.",
        "Carbon dioxide reflects visible sunlight back onto the Earth's surface.",
        "Carbon dioxide reacts with oxygen in an exothermic reaction that heats the air.",
      ],
      answerIndex: 1,
      optionFeedback: [
        "A common mix-up: ozone depletion (caused by CFCs) lets in more ultraviolet; it is a separate problem from the greenhouse effect.",
        "The Earth's surface emits infrared radiation; CO₂ absorbs and re-emits it, keeping heat in the lower atmosphere.",
        "CO₂ is transparent to visible light; its effect is on the infrared radiation given off by the warm Earth.",
        "Carbon dioxide does not react with oxygen — carbon is already fully oxidised in CO₂.",
      ],
      explanation:
        "Sunlight warms the Earth's surface, which then emits infrared radiation. Greenhouse gases such as CO₂, methane and water vapour absorb this infrared and re-emit it, so less heat escapes to space. Burning fossil fuels raises CO₂ levels, enhancing the greenhouse effect and causing climate change.",
      hints: [
        "What type of radiation does the warm Earth give off?",
        "Greenhouse gases trap heat on its way OUT, not on its way in.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "in-m16",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "core",
      question: "An iron nail is left in blue copper(II) sulfate solution. Which observations are made?",
      options: [
        "The nail becomes coated in a silver-grey solid and the solution stays blue.",
        "No change, because iron is less reactive than copper.",
        "The solution turns colourless and bubbles of hydrogen form.",
        "A pink-brown coating forms on the nail and the solution turns pale green.",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Copper is pink-brown, not silver-grey, and as Cu²⁺ ions are used up the blue colour fades.",
        "Iron is MORE reactive than copper (above it in the series), so a displacement reaction does happen.",
        "No hydrogen forms — this is metal displacement, not a metal + acid reaction; and iron(II) sulfate solution is pale green, not colourless.",
        "Fe + CuSO₄ → FeSO₄ + Cu: copper metal coats the nail and the solution changes from blue to pale green as iron(II) ions form.",
      ],
      explanation:
        "A more reactive metal displaces a less reactive metal from a solution of its salt. Ionic equation: Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Blue Cu²⁺ is replaced by pale green Fe²⁺, and pink-brown copper is deposited. (With zinc instead of iron the solution would become colourless.)",
      hints: [
        "Is iron above or below copper in the reactivity series?",
        "What colour is copper metal, and what colour are iron(II) ions in solution?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "in-m17",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "core",
      question: "Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)\nWhich species is the oxidising agent in this reaction?",
      options: ["Zn", "Zn²⁺", "Cu²⁺", "Cu"],
      answerIndex: 2,
      optionFeedback: [
        "Zinc loses electrons and is oxidised, so it is the reducing agent.",
        "Zn²⁺ is a product; the oxidising agent is a reactant that gains electrons.",
        "Cu²⁺ gains two electrons (Cu²⁺ + 2e⁻ → Cu), so it is reduced — and a species that is reduced is the oxidising agent.",
        "Copper metal is a product, formed when the oxidising agent is reduced.",
      ],
      explanation:
        "An oxidising agent takes electrons from something else, so it is itself reduced. Here Cu²⁺ takes 2 electrons from Zn: Cu²⁺ is the oxidising agent (reduced) and Zn is the reducing agent (oxidised).",
      hints: [
        "Write the two half-equations. Which reactant gains electrons?",
        "The oxidising agent is the reactant that gets reduced.",
      ],
      strategy: "Think about electrons",
    },
    {
      id: "in-m18",
      topic: "inorganic",
      section: "inorganic-metals",
      difficulty: "core",
      question: "Why is limestone added to the blast furnace?",
      options: [
        "to provide the carbon that reduces iron(III) oxide",
        "to remove silica impurities by forming slag",
        "to lower the melting point of the iron ore",
        "to react with carbon monoxide to make more carbon dioxide",
      ],
      answerIndex: 1,
      optionFeedback: [
        "The carbon comes from coke; limestone is calcium carbonate and is not the reducing agent.",
        "CaCO₃ → CaO + CO₂, then CaO + SiO₂ → CaSiO₃: calcium oxide removes the sand (silica) as molten slag.",
        "Lowering the melting point is the job of cryolite in aluminium extraction — don't mix the two processes up.",
        "Limestone decomposes to give some CO₂, but its purpose is to remove the acidic impurity silica.",
      ],
      explanation:
        "In the furnace limestone decomposes: CaCO₃ → CaO + CO₂. Calcium oxide is a basic oxide and reacts with silicon dioxide (an acidic impurity from the ore): CaO + SiO₂ → CaSiO₃. This molten slag floats on the iron and is tapped off.",
      hints: [
        "Iron ore is not pure — what is the main impurity in it?",
        "Calcium oxide is basic; silicon dioxide is acidic. What happens when they meet?",
      ],
      strategy: "Recall the definition",
    },

    // ───────── CHALLENGE ─────────
    {
      id: "in-m19",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "challenge",
      question: "A steel pipeline buried in damp soil is connected by a wire to a block of magnesium. Which statement best explains why the steel does not rust?",
      options: [
        "Magnesium is more reactive than iron, so it loses electrons and is oxidised instead of iron.",
        "Magnesium forms a coating over the steel that keeps out water and oxygen.",
        "Magnesium is less reactive than iron, so it does not corrode and protects the iron.",
        "Magnesium reduces any rust that forms back into iron.",
      ],
      answerIndex: 0,
      optionFeedback: [
        "This is sacrificial protection: magnesium is oxidised (Mg → Mg²⁺ + 2e⁻) in preference to iron, so the iron stays unoxidised.",
        "This is a barrier method — but the magnesium here is a separate block, not a coating, so it cannot be keeping out water and oxygen.",
        "Magnesium is MORE reactive than iron, and a less reactive metal could not give sacrificial protection.",
        "The magnesium stops rust forming in the first place; it does not reverse rusting.",
      ],
      explanation:
        "In sacrificial protection a more reactive metal (Mg or Zn) is attached to iron. Because it loses electrons more readily, it is oxidised instead of the iron. The magnesium block slowly corrodes away and must be replaced, but the pipeline does not rust.",
      hints: [
        "The magnesium is not touching all of the pipe, so it is not a barrier.",
        "Compare the positions of magnesium and iron in the reactivity series.",
        "Rusting is oxidation of iron. Which metal gives up electrons more easily?",
      ],
      strategy: "Think about electrons",
    },
    {
      id: "in-m20",
      topic: "inorganic",
      section: "inorganic-reactivity",
      difficulty: "challenge",
      question: "A student sets up four tubes, each containing an iron nail, and leaves them for a week. Which tube shows that water alone, without oxygen, does not cause rusting?",
      table: {
        headers: ["Tube", "Contents", "Result after one week"],
        rows: [
          ["1", "tap water, open to air", "rusted"],
          ["2", "boiled water with a layer of oil, stoppered", "no rust"],
          ["3", "anhydrous calcium chloride, stoppered", "no rust"],
          ["4", "salt water, open to air", "rusted badly"],
        ],
      },
      options: ["Tube 1", "Tube 2", "Tube 3", "Tube 4"],
      answerIndex: 1,
      optionFeedback: [
        "Tube 1 has both water and oxygen; it is the control showing rusting does happen.",
        "Boiling removed the dissolved oxygen and the oil stopped air re-dissolving, so the nail had water but no oxygen — and it did not rust.",
        "Tube 3 has air (oxygen) but no water; it shows that oxygen alone does not cause rusting.",
        "Tube 4 has both water and oxygen; it shows that salt speeds up rusting.",
      ],
      explanation:
        "Each tube removes one factor. Tube 2 has water but no oxygen (no rust); tube 3 has oxygen but no water (no rust); tube 1 has both (rust). Together they show that rusting needs both water and oxygen. Tube 4 adds an extra finding: salt increases the rate.",
      hints: [
        "You need a tube where water IS present but oxygen is NOT.",
        "What does boiling the water do to dissolved gases?",
        "Why is the oil layer needed after boiling?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "in-m21",
      topic: "inorganic",
      section: "inorganic-group7",
      difficulty: "challenge",
      question: "Cl₂(aq) + 2Br⁻(aq) → 2Cl⁻(aq) + Br₂(aq)\nWhich half-equation shows the OXIDATION in this reaction?",
      options: [
        "2Br⁻ → Br₂ + 2e⁻",
        "Cl₂ + 2e⁻ → 2Cl⁻",
        "2Br⁻ + 2e⁻ → Br₂",
        "Br₂ + 2e⁻ → 2Br⁻",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Bromide ions lose electrons to form bromine molecules — loss of electrons is oxidation.",
        "This is a correct half-equation, but chlorine GAINS electrons here, so it shows reduction.",
        "Charges don't balance: left side is 2− + 2− = 4−, right side is 0. Oxidation removes electrons, so they appear on the right.",
        "This is the reverse reaction (bromine being reduced), which does not happen here.",
      ],
      explanation:
        "Split the reaction into halves. Chlorine gains electrons: Cl₂ + 2e⁻ → 2Cl⁻ (reduction; Cl₂ is the oxidising agent). Bromide ions lose electrons: 2Br⁻ → Br₂ + 2e⁻ (oxidation; Br⁻ is the reducing agent). In an oxidation half-equation, electrons appear as a product.",
      hints: [
        "Which reactant ends up with fewer electrons than it started with?",
        "OILRIG: oxidation is loss of electrons — so are electrons on the left or the right?",
        "Check that charge is balanced on each side of your chosen half-equation.",
      ],
      strategy: "Think about electrons",
    },
    {
      id: "in-m22",
      topic: "inorganic",
      section: "inorganic-metals",
      difficulty: "challenge",
      question: "In the extraction of aluminium, why do the carbon anodes have to be replaced regularly?",
      options: [
        "Aluminium builds up on the anodes and stops the current flowing.",
        "The carbon anodes dissolve in the molten cryolite.",
        "Oxygen formed at the anodes reacts with the hot carbon to form carbon dioxide.",
        "Aluminium ions are attracted to the anodes and react with the carbon.",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Aluminium forms at the CATHODE (negative), not the anode — positive Al³⁺ ions are attracted to the negative electrode.",
        "Carbon does not dissolve in cryolite; the anodes are worn away by a chemical reaction.",
        "At the anode 2O²⁻ → O₂ + 4e⁻; at about 950 °C the oxygen reacts with the carbon (C + O₂ → CO₂), so the anodes burn away.",
        "Al³⁺ ions are positive, so they move to the negative cathode, not the positive anode.",
      ],
      explanation:
        "Oxide ions are oxidised at the positive anode: 2O²⁻ → O₂ + 4e⁻. The anodes are made of carbon and the cell is very hot, so the oxygen reacts with them: C(s) + O₂(g) → CO₂(g). The anodes gradually burn away and must be replaced — one reason the process is expensive.",
      hints: [
        "Which product forms at the positive electrode?",
        "What is the anode made of, and what happens to that material in oxygen at high temperature?",
        "Positive ions go to the negative electrode — use that to rule options out.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "in-m23",
      topic: "inorganic",
      section: "inorganic-metals",
      difficulty: "challenge",
      question: "Fe₂O₃ + 3CO → 2Fe + 3CO₂\nWhat is the maximum mass of iron that can be made from 480 tonnes of iron(III) oxide? (Ar: Fe = 56, O = 16)",
      options: ["168 tonnes", "504 tonnes", "240 tonnes", "336 tonnes"],
      answerIndex: 3,
      optionFeedback: [
        "This is what you get if you forget that 1 Fe₂O₃ gives 2 Fe — you used a 1 : 1 ratio.",
        "This uses a 1 : 3 ratio — you have taken the 3 from CO instead of the 2 in front of Fe.",
        "Halving the mass is a guess; the mass of iron depends on the fraction of Fe₂O₃ that is iron (112/160).",
        "Mr Fe₂O₃ = 160; 480 ÷ 160 = 3 (million) mol; ratio 1 : 2 gives 6 mol Fe; 6 × 56 = 336 tonnes.",
      ],
      explanation:
        "Work in tonne-moles (the units cancel the same way as grams):\n- Mr Fe₂O₃ = 2 × 56 + 3 × 16 = 160\n- moles Fe₂O₃ = 480 ÷ 160 = 3\n- ratio Fe₂O₃ : Fe = 1 : 2 → moles Fe = 6\n- mass Fe = 6 × 56 = 336 tonnes\nCheck: iron is 112/160 = 70% of Fe₂O₃, and 70% of 480 = 336.",
      hints: [
        "Start by working out the Mr of Fe₂O₃.",
        "Use the balanced equation: how many Fe for each Fe₂O₃?",
        "Tonnes behave just like grams in this calculation — no conversion needed.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "in-m24",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "challenge",
      question: "12.35 g of copper(II) carbonate is heated until it has completely decomposed. CuCO₃ → CuO + CO₂\nWhat mass of solid remains? (Ar: Cu = 63.5, C = 12, O = 16)",
      options: ["4.40 g", "12.35 g", "6.35 g", "7.95 g"],
      answerIndex: 3,
      optionFeedback: [
        "4.40 g is the mass of carbon dioxide given off (0.100 × 44), which escapes as a gas — not the solid left behind.",
        "The mass falls because carbon dioxide gas escapes — the solid cannot stay at 12.35 g.",
        "6.35 g is the mass of copper alone (0.100 × 63.5), but the solid is copper(II) oxide, which also contains oxygen.",
        "Mr CuCO₃ = 123.5, so 12.35 ÷ 123.5 = 0.100 mol; 0.100 mol CuO × 79.5 = 7.95 g.",
      ],
      explanation:
        "- Mr CuCO₃ = 63.5 + 12 + 3 × 16 = 123.5\n- moles = 12.35 ÷ 123.5 = 0.100 mol\n- ratio 1 : 1 → 0.100 mol CuO; Mr CuO = 79.5\n- mass CuO = 0.100 × 79.5 = 7.95 g\nCheck by conservation of mass: 12.35 − 4.40 (CO₂) = 7.95 g.",
      hints: [
        "Which product is the solid, and which escapes?",
        "Find the moles of CuCO₃ first.",
        "Use the 1 : 1 ratio, then multiply by the Mr of the solid product.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "in-m25",
      topic: "inorganic",
      section: "inorganic-group1",
      difficulty: "core",
      question: "Lithium, sodium and potassium are each added to water containing universal indicator. Which observation is evidence that they belong to the same family of elements?",
      options: [
        "Potassium reacts much more vigorously than lithium",
        "Only sodium melts into a ball on the surface",
        "Each one fizzes and turns the indicator blue or purple",
        "Only potassium gives a lilac flame",
      ],
      answerIndex: 2,
      optionFeedback: [
        "This is a DIFFERENCE between them (the reactivity trend), not a similarity — it shows the trend down the group, not that they are a family.",
        "This picks out a difference between the metals, so it cannot show what they have in common.",
        "Every one gives off hydrogen (fizzing) and forms an alkaline hydroxide solution — the same reaction pattern, which is the evidence for a family.",
        "Again a difference — the lilac flame belongs to potassium only (from burning hydrogen and potassium vapour).",
      ],
      explanation:
        "A family (group) of elements shows SIMILAR chemical reactions. Li, Na and K all react with water to give hydrogen and a metal hydroxide, MOH, which makes the water alkaline: 2M(s) + 2H₂O(l) → 2MOH(aq) + H₂(g). They behave alike because each atom has one outer electron. The differences between them (vigour of reaction) form a trend down the group.",
      hints: ["A family is shown by what the elements have in COMMON.", "Which option is true for all three metals?"],
      strategy: "Compare and contrast",
    },
    {
      id: "in-m26",
      topic: "inorganic",
      section: "inorganic-group7",
      difficulty: "core",
      question: "Astatine is below iodine in Group 7. Which row is the best prediction for astatine?",
      table: {
        headers: ["Option", "State at room temperature", "Colour", "Reactivity compared with iodine"],
        rows: [
          ["A", "gas", "pale yellow", "more reactive"],
          ["B", "liquid", "red-brown", "less reactive"],
          ["C", "solid", "black", "more reactive"],
          ["D", "solid", "black", "less reactive"],
        ],
      },
      options: ["A", "B", "C", "D"],
      answerIndex: 3,
      optionFeedback: [
        "These are the properties of fluorine, at the TOP of the group. Going down, the halogens get darker and change from gas to solid.",
        "This matches bromine. Iodine is already a solid, so the element below it will be a solid too.",
        "State and colour are right, but reactivity DECREASES down Group 7 — the opposite of Group 1.",
        "Melting point rises and colour darkens down the group, so astatine is a black solid; reactivity decreases down Group 7, so it is less reactive than iodine.",
      ],
      explanation:
        "Down Group 7 the molecules get bigger, intermolecular forces get stronger, so melting and boiling points rise (gas → liquid → solid) and the colour darkens (pale yellow → yellow-green → red-brown → grey-black). Reactivity decreases because the outer shell is further from the nucleus and more shielded, so an extra electron is gained less easily. Astatine: black solid, least reactive.",
      hints: ["What happens to the state and colour from chlorine to bromine to iodine?", "Does reactivity go up or down in Group 7 — is it the same direction as Group 1?"],
      strategy: "Apply it to a new situation",
    },
    {
      id: "in-m27",
      topic: "inorganic",
      section: "inorganic-air",
      difficulty: "core",
      question: "Element Q burns in oxygen. Its oxide dissolves in water to give a solution of pH 3. Which statement is correct?",
      options: [
        "Q is a non-metal, such as sulfur",
        "Q is a metal, such as magnesium",
        "Q is hydrogen, because water is formed",
        "Q is a metal, because it burns brightly",
      ],
      answerIndex: 0,
      optionFeedback: [
        "pH 3 means an acidic oxide, and acidic oxides come from non-metals: S + O₂ → SO₂, which dissolves to give an acidic solution.",
        "Magnesium oxide is a basic oxide — in water it gives a slightly ALKALINE solution (pH above 7), not pH 3.",
        "Hydrogen burns to form water, which is neutral (pH 7), so it cannot give a pH 3 solution.",
        "Many elements burn brightly in oxygen; the acid–base character of the oxide, not the flame, tells you metal or non-metal.",
      ],
      explanation:
        "You can classify an element from its oxide. Metal oxides are basic (soluble ones give alkaline solutions, e.g. MgO). Non-metal oxides are usually acidic (SO₂, CO₂ give acidic solutions). Hydrogen burns to give water, a neutral oxide: 2H₂(g) + O₂(g) → 2H₂O(l). pH 3 → acidic oxide → non-metal.",
      hints: ["Is a solution of pH 3 acidic, neutral or alkaline?", "Which type of element forms acidic oxides?"],
      strategy: "Read the data carefully",
    },
  ],
};
