import type { MCQ, QuestionSet } from "../../types";

export const mcq: QuestionSet<MCQ> = {
  id: "mcq-calc",
  title: "Multiple choice · Formulae, Equations & Moles",
  subtitle: "Formulae, ionic equations, reacting masses, % yield, gas volumes and titration calculations — distractors built from real slips.",
  topic: "calc",
  questions: [
    {
      id: "ca-m01",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "warmup",
      question: "Aluminium ions are Al³⁺ and sulfate ions are SO₄²⁻. What is the formula of aluminium sulfate?",
      options: ["AlSO₄", "Al₃(SO₄)₂", "Al₂(SO₄)₃", "Al₂SO₄"],
      answerIndex: 2,
      optionFeedback: [
        "Tempting because it just joins the two ions, but the charges don't cancel: +3 and −2 leaves an overall charge of +1.",
        "This swaps the charges onto the wrong ions: 3 × (+3) = +9 and 2 × (−2) = −4, which doesn't balance.",
        "Two Al³⁺ give +6 and three SO₄²⁻ give −6, so the compound is neutral.",
        "Two Al³⁺ give +6 but one SO₄²⁻ is only −2 — and without brackets you can't show more than one sulfate ion.",
      ],
      explanation:
        "An ionic compound has no overall charge. The lowest common multiple of 3 and 2 is 6, so you need 2 × Al³⁺ (+6) and 3 × SO₄²⁻ (−6). Brackets show that the whole sulfate ion is multiplied by 3: Al₂(SO₄)₃.",
      hints: ["How many of each ion do you need for the positive and negative charges to add up to zero?"],
      strategy: "Balance the equation",
    },
    {
      id: "ca-m02",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "warmup",
      question: "Which is the ionic equation for the reaction between hydrochloric acid and sodium hydroxide solution?",
      options: [
        "H⁺(aq) + OH⁻(aq) → H₂O(l)",
        "Na⁺(aq) + Cl⁻(aq) → NaCl(aq)",
        "HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l)",
        "H⁺(aq) + Cl⁻(aq) → HCl(aq)",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Hydrogen ions from the acid join hydroxide ions from the alkali to make water — the only change in any neutralisation.",
        "Na⁺ and Cl⁻ are the spectator ions: they stay dissolved and unchanged, so they are left out of the ionic equation.",
        "This is the full balanced equation, not the ionic equation — the dissolved ionic compounds haven't been split and the spectators removed.",
        "This is the wrong way round: the acid gives out H⁺ ions in solution; nothing re-forms HCl molecules.",
      ],
      explanation:
        "Write the ions: H⁺ + Cl⁻ + Na⁺ + OH⁻ → Na⁺ + Cl⁻ + H₂O. Na⁺ and Cl⁻ appear unchanged on both sides, so they are spectators. What is left, H⁺(aq) + OH⁻(aq) → H₂O(l), is the ionic equation for every acid–alkali neutralisation.",
      hints: ["Split everything that is (aq) into ions and cross out what appears unchanged on both sides."],
      strategy: "Recall the definition",
    },
    {
      id: "ca-m03",
      topic: "calc",
      section: "calc-moles",
      difficulty: "warmup",
      question: "What is the relative formula mass (Mr) of hydrated copper(II) sulfate, CuSO₄·5H₂O? (Ar: H = 1, O = 16, S = 32, Cu = 63.5)",
      options: ["159.5", "177.5", "244.5", "249.5"],
      answerIndex: 3,
      optionFeedback: [
        "This is the Mr of anhydrous CuSO₄ only — you have left out the five waters of crystallisation.",
        "This adds only one water molecule (159.5 + 18). The 5 multiplies the whole H₂O.",
        "This uses 17 for water (5 × 17 = 85) — H₂O has two hydrogens, so it is 2 + 16 = 18.",
        "63.5 + 32 + 4 × 16 = 159.5, plus 5 × 18 = 90, gives 249.5.",
      ],
      explanation:
        "The dot in CuSO₄·5H₂O means 'add': Mr = Mr(CuSO₄) + 5 × Mr(H₂O).\nCuSO₄ = 63.5 + 32 + (4 × 16) = 159.5\n5H₂O = 5 × (2 × 1 + 16) = 90\nMr = 159.5 + 90 = 249.5",
      hints: ["Work out CuSO₄ and 5 × H₂O separately, then add them."],
      strategy: "Follow the method step by step",
    },
    {
      id: "ca-m04",
      topic: "calc",
      section: "calc-moles",
      difficulty: "warmup",
      question: "How many moles are there in 8.0 g of sodium hydroxide, NaOH? (Ar: H = 1, O = 16, Na = 23)",
      options: ["5.0 mol", "0.20 mol", "320 mol", "0.35 mol"],
      answerIndex: 1,
      optionFeedback: [
        "This is Mr ÷ mass (40 ÷ 8.0) — the formula upside down. Moles = mass ÷ Mr.",
        "Mr NaOH = 23 + 16 + 1 = 40, so moles = 8.0 ÷ 40 = 0.20 mol.",
        "This multiplies mass by Mr (8.0 × 40). Multiplying gives the mass from moles, not the other way.",
        "This divides by the Ar of sodium (8.0 ÷ 23) instead of the Mr of the whole compound.",
      ],
      explanation:
        "moles = mass ÷ Mr.\nMr(NaOH) = 23 + 16 + 1 = 40\nmoles = 8.0 ÷ 40 = 0.20 mol\nAlways use the Mr of the whole formula, never the Ar of one element.",
      hints: ["Find the Mr of NaOH first, then use moles = mass ÷ Mr."],
      strategy: "Recall the definition",
    },
    {
      id: "ca-m05",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "warmup",
      question: "What volume does 0.50 mol of carbon dioxide gas occupy at room temperature and pressure? (Molar gas volume = 24 dm³ at rtp)",
      options: ["0.021 dm³", "48 dm³", "12 dm³", "22 dm³"],
      answerIndex: 2,
      optionFeedback: [
        "This is 0.50 ÷ 24 — you divided when you should multiply. Volume = moles × 24.",
        "This is 24 ÷ 0.50. Half a mole must take up less space than one mole, not more.",
        "Volume = moles × 24 = 0.50 × 24 = 12 dm³.",
        "This is 0.50 × 44, the mass in grams of CO₂ — the volume at rtp doesn't depend on Mr.",
      ],
      explanation:
        "At rtp one mole of ANY gas occupies 24 dm³, whatever its Mr.\nvolume = moles × 24 = 0.50 × 24 = 12 dm³\nSanity check: half a mole should take up half of 24 dm³.",
      hints: ["One mole occupies 24 dm³. How much does half a mole occupy?"],
      strategy: "Check the units",
    },
    {
      id: "ca-m06",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "warmup",
      question: "0.10 mol of sodium chloride is dissolved in water to make 250 cm³ of solution. What is the concentration of the solution?",
      options: ["0.025 mol/dm³", "0.0004 mol/dm³", "25 mol/dm³", "0.40 mol/dm³"],
      answerIndex: 3,
      optionFeedback: [
        "This multiplies moles by volume (0.10 × 0.250). Concentration = moles ÷ volume.",
        "This divides by 250 without converting cm³ to dm³ — the answer is 1000 times too small.",
        "This multiplies 0.10 by 250 — both the wrong operation and the wrong units.",
        "250 cm³ = 0.250 dm³, and 0.10 ÷ 0.250 = 0.40 mol/dm³.",
      ],
      explanation:
        "Concentration (mol/dm³) = moles ÷ volume in dm³.\n250 cm³ ÷ 1000 = 0.250 dm³\n0.10 ÷ 0.250 = 0.40 mol/dm³\nSanity check: a quarter of a litre holding 0.10 mol is four times as concentrated as 1 dm³ holding 0.10 mol.",
      hints: ["Convert the volume to dm³ first (÷ 1000)."],
      strategy: "Check the units",
    },
    {
      id: "ca-m07",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "core",
      question: "In the blast furnace: a Fe₂O₃ + b CO → c Fe + d CO₂. Which values of a, b, c and d balance the equation?",
      options: ["a = 1, b = 1, c = 2, d = 1", "a = 1, b = 3, c = 2, d = 3", "a = 2, b = 3, c = 4, d = 3", "a = 1, b = 3, c = 2, d = 2"],
      answerIndex: 1,
      optionFeedback: [
        "Iron balances (2 = 2) but oxygen doesn't: left has 3 + 1 = 4 O, right has only 2.",
        "Fe: 2 = 2. C: 3 = 3. O: 3 + 3 = 6 on the left and 3 × 2 = 6 on the right.",
        "Iron balances (4 = 4) but oxygen doesn't: left has 6 + 3 = 9 O, right only 6.",
        "Carbon doesn't balance: 3 C on the left but only 2 on the right (and O is 6 vs 4).",
      ],
      explanation:
        "Balance Fe first: 1 Fe₂O₃ → 2Fe. Each CO picks up one O to become CO₂, and Fe₂O₃ has 3 O to give away, so you need 3CO → 3CO₂.\nFe₂O₃ + 3CO → 2Fe + 3CO₂\nCheck every element: Fe 2/2, C 3/3, O 6/6.",
      hints: ["Start with iron.", "Each CO molecule gains one oxygen atom to become CO₂. How many oxygens does Fe₂O₃ have to give away?"],
      strategy: "Balance the equation",
    },
    {
      id: "ca-m08",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "core",
      question: "Silver nitrate solution is added to sodium bromide solution and a cream precipitate forms. Which is the correct ionic equation?",
      options: [
        "Ag⁺(aq) + Br⁻(aq) → AgBr(s)",
        "Na⁺(aq) + NO₃⁻(aq) → NaNO₃(aq)",
        "Ag⁺(aq) + Br⁻(aq) → AgBr(aq)",
        "AgNO₃(aq) + Br⁻(aq) → AgBr(s) + NO₃⁻(aq)",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Silver and bromide ions join to form the insoluble solid silver bromide — the precipitate.",
        "These are the spectator ions; sodium nitrate stays dissolved, so nothing actually happens to them.",
        "The species are right but the state symbol isn't — a precipitate is a solid, (s), not (aq).",
        "AgNO₃(aq) should be split into Ag⁺ and NO₃⁻; then NO₃⁻ cancels as a spectator.",
      ],
      explanation:
        "AgNO₃(aq) + NaBr(aq) → AgBr(s) + NaNO₃(aq).\nSplit the aqueous compounds into ions; Na⁺ and NO₃⁻ appear unchanged on both sides, so they are spectators.\nIonic equation: Ag⁺(aq) + Br⁻(aq) → AgBr(s). The precipitate always takes (s).",
      hints: ["Which product is the precipitate?", "Split the (aq) compounds into ions and remove the ions that don't change."],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ca-m09",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "core",
      question: "BaCl₂(aq) + K₂SO₄(aq) → BaSO₄(s) + 2KCl(aq). Which ions are the spectator ions?",
      options: ["Ba²⁺ and SO₄²⁻", "K⁺ only", "K⁺ and Cl⁻", "Ba²⁺ and Cl⁻"],
      answerIndex: 2,
      optionFeedback: [
        "These are the ions that DO react — they combine to form the barium sulfate precipitate.",
        "K⁺ is a spectator, but so is Cl⁻: it starts in BaCl₂(aq) and ends in KCl(aq), still a free ion.",
        "K⁺ and Cl⁻ are dissolved before and after the reaction and are unchanged.",
        "Ba²⁺ leaves the solution as BaSO₄(s), so it is not a spectator.",
      ],
      explanation:
        "Spectator ions are present in the solution but do not change. Ba²⁺ and SO₄²⁻ come out of solution as the solid BaSO₄, so they react. K⁺ and Cl⁻ are aqueous on both sides, so they are spectators. Ionic equation: Ba²⁺(aq) + SO₄²⁻(aq) → BaSO₄(s).",
      hints: ["Which ions end up in the solid?", "Spectators are still (aq) on the product side."],
      strategy: "Think about particles",
    },
    {
      id: "ca-m10",
      topic: "calc",
      section: "calc-formulae",
      difficulty: "core",
      question: "Magnesium ribbon reacts with dilute hydrochloric acid: Mg + 2HCl → MgCl₂ + H₂. Which set of state symbols is correct, in the order Mg, HCl, MgCl₂, H₂?",
      options: ["(s), (l), (aq), (g)", "(s), (aq), (s), (g)", "(s), (aq), (aq), (l)", "(s), (aq), (aq), (g)"],
      answerIndex: 3,
      optionFeedback: [
        "Dilute hydrochloric acid is hydrogen chloride dissolved in water, so it is (aq), not (l).",
        "Magnesium chloride is soluble — it stays dissolved in the solution, so it is (aq).",
        "Hydrogen is a gas at room temperature — that's why you see fizzing.",
        "Solid metal, dissolved acid, dissolved soluble salt, and hydrogen gas bubbling off.",
      ],
      explanation:
        "(s) solid, (l) pure liquid, (g) gas, (aq) dissolved in water. A dilute acid is always (aq). Chlorides are soluble (except silver and lead), so MgCl₂ is (aq). The fizzing is hydrogen gas, (g).\nMg(s) + 2HCl(aq) → MgCl₂(aq) + H₂(g)",
      hints: ["Is a dilute acid a pure liquid or a solution?", "Is magnesium chloride soluble? What causes the fizzing?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ca-m11",
      topic: "calc",
      section: "calc-moles",
      difficulty: "core",
      question: "Calcium carbonate decomposes on heating: CaCO₃ → CaO + CO₂. What mass of calcium oxide is formed from 25.0 g of calcium carbonate? (Ar: C = 12, O = 16, Ca = 40)",
      options: ["14.0 g", "11.0 g", "10.0 g", "28.0 g"],
      answerIndex: 0,
      optionFeedback: [
        "Moles CaCO₃ = 25.0 ÷ 100 = 0.250; ratio 1 : 1; mass CaO = 0.250 × 56 = 14.0 g.",
        "This is the mass of carbon dioxide (0.250 × 44) — the other product.",
        "This uses the Ar of calcium (0.250 × 40) instead of the Mr of CaO.",
        "This doubles the moles — the ratio CaCO₃ : CaO is 1 : 1, not 1 : 2.",
      ],
      explanation:
        "Mr CaCO₃ = 40 + 12 + 48 = 100; Mr CaO = 40 + 16 = 56.\nMoles CaCO₃ = 25.0 ÷ 100 = 0.250 mol\nRatio 1 : 1 → 0.250 mol CaO\nMass CaO = 0.250 × 56 = 14.0 g\nCheck: 14.0 g CaO + 11.0 g CO₂ = 25.0 g — mass is conserved.",
      hints: ["Find moles of CaCO₃ first.", "Use the 1 : 1 ratio, then multiply by the Mr of CaO."],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m12",
      topic: "calc",
      section: "calc-moles",
      difficulty: "core",
      question: "The theoretical yield of a salt is 16.0 g. A student obtains 12.4 g of dry crystals. What is the percentage yield?",
      options: ["129%", "77.5%", "22.5%", "3.6%"],
      answerIndex: 1,
      optionFeedback: [
        "This is theoretical ÷ actual — the fraction upside down. A percentage yield can never be over 100%.",
        "12.4 ÷ 16.0 × 100 = 77.5%.",
        "This is the percentage LOST (100 − 77.5), not the percentage obtained.",
        "This is just the difference in mass (16.0 − 12.4 = 3.6 g), not a percentage.",
      ],
      explanation:
        "% yield = actual yield ÷ theoretical yield × 100\n= 12.4 ÷ 16.0 × 100 = 77.5%\nThe actual yield is always the smaller number, so the answer must be below 100%.",
      hints: ["Which is bigger — what you got or what you could have got?", "Put actual over theoretical."],
      strategy: "Recall the definition",
    },
    {
      id: "ca-m13",
      topic: "calc",
      section: "calc-moles",
      difficulty: "core",
      question: "5.6 g of iron combines with 2.4 g of oxygen to form an oxide. What is the empirical formula of the oxide? (Ar: O = 16, Fe = 56)",
      options: ["FeO", "Fe₃O₄", "Fe₂O₃", "Fe₄O₃"],
      answerIndex: 2,
      optionFeedback: [
        "This assumes a 1 : 1 ratio without calculating: the moles are 0.10 Fe and 0.15 O, not equal.",
        "A real iron oxide, but not the one these masses give: the ratio here is 0.10 : 0.15 = 2 : 3.",
        "Fe 5.6 ÷ 56 = 0.10, O 2.4 ÷ 16 = 0.15; 0.10 : 0.15 = 2 : 3.",
        "This divides oxygen's mass by 32 (the Mr of O₂). In an empirical formula you count O atoms, so use Ar = 16.",
      ],
      explanation:
        "Divide each mass by its Ar, then find the simplest whole-number ratio.\nFe: 5.6 ÷ 56 = 0.10 mol\nO: 2.4 ÷ 16 = 0.15 mol\nDivide by the smallest: 1 : 1.5 → double → 2 : 3\nEmpirical formula = Fe₂O₃",
      hints: ["Convert each mass to moles of atoms using Ar.", "If the ratio comes out as 1 : 1.5, what do you multiply by?"],
      strategy: "Follow the method step by step",
    },
    {
      id: "ca-m14",
      topic: "calc",
      section: "calc-moles",
      difficulty: "core",
      question: "2.4 g of magnesium is added to a solution containing 0.10 mol of hydrochloric acid. Mg + 2HCl → MgCl₂ + H₂. Which statement is correct? (Ar: Mg = 24)",
      options: [
        "Magnesium is limiting; 0.10 mol of H₂ forms",
        "Neither is in excess; 0.10 mol of H₂ forms",
        "HCl is limiting; 0.10 mol of H₂ forms",
        "HCl is limiting; 0.050 mol of H₂ forms",
      ],
      answerIndex: 3,
      optionFeedback: [
        "There are 0.10 mol of Mg, but it would need 0.20 mol of HCl — there is only 0.10 mol of acid, so the acid runs out first.",
        "Equal numbers of moles are not 'just enough' here — the equation needs 2 mol of HCl for every 1 mol of Mg.",
        "HCl is limiting, but you forgot the ratio: 2HCl gives 1H₂, so 0.10 mol HCl gives only 0.050 mol H₂.",
        "0.10 mol Mg needs 0.20 mol HCl, so the 0.10 mol of HCl runs out first and gives 0.10 ÷ 2 = 0.050 mol H₂.",
      ],
      explanation:
        "Moles Mg = 2.4 ÷ 24 = 0.10 mol. To react completely it needs 2 × 0.10 = 0.20 mol HCl, but only 0.10 mol is present, so HCl is the limiting reactant and Mg is in excess.\nH₂ from HCl: ratio 2 : 1 → 0.10 ÷ 2 = 0.050 mol H₂.",
      hints: ["How many moles of HCl would 0.10 mol of Mg need?", "Calculate the product from the reactant that runs out — and use its ratio."],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m15",
      topic: "calc",
      section: "calc-moles",
      difficulty: "core",
      question: "Hydrated sodium carbonate, Na₂CO₃·xH₂O, has Mr = 286. What is the value of x? (Ar: H = 1, C = 12, O = 16, Na = 23)",
      options: ["10", "16", "12", "11"],
      answerIndex: 0,
      optionFeedback: [
        "Na₂CO₃ = 46 + 12 + 48 = 106; water = 286 − 106 = 180; 180 ÷ 18 = 10.",
        "This divides the whole Mr by 18 (286 ÷ 18 ≈ 16) — you must subtract the Na₂CO₃ first.",
        "This counts only one oxygen in carbonate (Na₂CO = 74, 212 ÷ 18 ≈ 12). Carbonate is CO₃.",
        "This counts only one sodium (NaCO₃ = 83, 203 ÷ 18 ≈ 11). The formula has Na₂.",
      ],
      explanation:
        "Mr(hydrated) = Mr(anhydrous) + x × 18.\nMr(Na₂CO₃) = 2 × 23 + 12 + 3 × 16 = 106\nMass of water in one formula unit = 286 − 106 = 180\nx = 180 ÷ 18 = 10, so the formula is Na₂CO₃·10H₂O (washing soda).",
      hints: ["Find the Mr of the anhydrous part first.", "The rest of the 286 is water — how many 18s is that?"],
      strategy: "Work backwards",
    },
    {
      id: "ca-m16",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "core",
      question: "1.20 g of magnesium reacts with excess hydrochloric acid: Mg + 2HCl → MgCl₂ + H₂. What volume of hydrogen forms at rtp? (Ar: Mg = 24; molar gas volume = 24 000 cm³ at rtp)",
      options: ["600 cm³", "1200 cm³", "2400 cm³", "1.20 cm³"],
      answerIndex: 1,
      optionFeedback: [
        "This halves the moles, as if the ratio were 2 Mg : 1 H₂. The 2 belongs to HCl — Mg : H₂ is 1 : 1.",
        "Moles Mg = 1.20 ÷ 24 = 0.0500; ratio 1 : 1; volume = 0.0500 × 24 000 = 1200 cm³.",
        "This doubles the moles using the HCl coefficient. Mg and H₂ are both '1' in the equation.",
        "The number 1.20 is right in dm³ — but in cm³ it is 1200. Check which unit the molar volume was in.",
      ],
      explanation:
        "Moles Mg = 1.20 ÷ 24 = 0.0500 mol\nRatio Mg : H₂ = 1 : 1 → 0.0500 mol H₂\nVolume = 0.0500 × 24 000 = 1200 cm³ (= 1.20 dm³)\nOnly look at the coefficients of the two substances you are linking — HCl isn't involved in this step.",
      hints: ["Moles of Mg first.", "Compare the coefficients of Mg and H₂ only, then use 24 000 cm³."],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m17",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "core",
      question: "A solution of sodium carbonate, Na₂CO₃, has a concentration of 0.250 mol/dm³. What is its concentration in g/dm³? (Ar: C = 12, O = 16, Na = 23)",
      options: ["424 g/dm³", "0.00236 g/dm³", "20.8 g/dm³", "26.5 g/dm³"],
      answerIndex: 3,
      optionFeedback: [
        "This is Mr ÷ concentration (106 ÷ 0.250). To go from mol/dm³ to g/dm³ you multiply by Mr.",
        "This is 0.250 ÷ 106 — dividing goes the wrong way (g/dm³ → mol/dm³).",
        "This uses NaCO₃ (Mr 83). Sodium carbonate has two sodium ions: Na₂CO₃, Mr 106.",
        "Mr Na₂CO₃ = 106, so 0.250 × 106 = 26.5 g/dm³.",
      ],
      explanation:
        "g/dm³ = mol/dm³ × Mr.\nMr(Na₂CO₃) = 2 × 23 + 12 + 3 × 16 = 106\n0.250 × 106 = 26.5 g/dm³\nThink of it as: 0.250 mol in each dm³, and each mole weighs 106 g.",
      hints: ["Each dm³ contains 0.250 mol. What is the mass of 0.250 mol?", "Check the formula — how many sodium ions balance one carbonate ion?"],
      strategy: "Check the units",
    },
    {
      id: "ca-m18",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "core",
      question: "25.0 cm³ of potassium hydroxide solution is exactly neutralised by 20.00 cm³ of 0.150 mol/dm³ hydrochloric acid. KOH + HCl → KCl + H₂O. What is the concentration of the potassium hydroxide?",
      options: ["0.188 mol/dm³", "0.00300 mol/dm³", "0.120 mol/dm³", "0.240 mol/dm³"],
      answerIndex: 2,
      optionFeedback: [
        "This puts the volumes the wrong way round (0.150 × 25.0 ÷ 20.00). Moles come from the ACID's volume.",
        "0.00300 mol is the number of moles of KOH — you still need to divide by its volume in dm³.",
        "Moles HCl = 0.150 × 0.02000 = 0.00300; 1 : 1 → 0.00300 mol KOH; 0.00300 ÷ 0.0250 = 0.120 mol/dm³.",
        "This uses a 1 : 2 ratio — KOH and HCl react 1 : 1.",
      ],
      explanation:
        "Moles HCl = 0.150 × (20.00 ÷ 1000) = 0.00300 mol\nRatio 1 : 1 → moles KOH = 0.00300 mol\nConcentration KOH = 0.00300 ÷ (25.0 ÷ 1000) = 0.120 mol/dm³\nSanity check: less acid volume than alkali volume was needed, so the alkali is weaker than the acid.",
      hints: ["Work out the moles of the solution you know everything about.", "Use the 1 : 1 ratio, then divide by 0.0250 dm³."],
      strategy: "Follow the method step by step",
    },
    {
      id: "ca-m19",
      topic: "calc",
      section: "calc-moles",
      difficulty: "challenge",
      question: "Zn + H₂SO₄ + 7H₂O → ZnSO₄·7H₂O + H₂. A student reacts 3.25 g of zinc completely and obtains 11.5 g of hydrated zinc sulfate crystals. What is the percentage yield? (Ar: H = 1, O = 16, S = 32, Zn = 65)",
      options: ["143%", "80.1%", "125%", "40.1%"],
      answerIndex: 1,
      optionFeedback: [
        "This uses the Mr of anhydrous ZnSO₄ (161) for the theoretical yield (8.05 g). The crystals contain 7H₂O, so use Mr 287.",
        "Moles Zn = 0.0500; theoretical = 0.0500 × 287 = 14.35 g; 11.5 ÷ 14.35 × 100 = 80.1%.",
        "This is theoretical ÷ actual (14.35 ÷ 11.5). A yield above 100% is a signal you inverted the fraction.",
        "This doubles the moles of product (theoretical 28.7 g). The ratio Zn : ZnSO₄·7H₂O is 1 : 1.",
      ],
      explanation:
        "Mr ZnSO₄·7H₂O = 65 + 32 + 64 + 7 × 18 = 287\nMoles Zn = 3.25 ÷ 65 = 0.0500 mol → 0.0500 mol of product (1 : 1)\nTheoretical yield = 0.0500 × 287 = 14.35 g\n% yield = 11.5 ÷ 14.35 × 100 = 80.1%\nThis is the same skill as the zinc nitrate question on your teacher's paper.",
      hints: [
        "Work out the Mr of the HYDRATED salt — include all seven waters.",
        "Find the theoretical yield from the moles of zinc.",
        "% yield = actual ÷ theoretical × 100.",
      ],
      strategy: "Follow the method step by step",
    },
    {
      id: "ca-m20",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "challenge",
      question: "25.0 cm³ of sodium hydroxide solution is neutralised by 18.60 cm³ of 0.0500 mol/dm³ sulfuric acid. H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. What is the concentration of the sodium hydroxide?",
      options: ["0.0744 mol/dm³", "0.0372 mol/dm³", "0.00186 mol/dm³", "0.134 mol/dm³"],
      answerIndex: 0,
      optionFeedback: [
        "Moles H₂SO₄ = 0.000930; × 2 = 0.00186 mol NaOH; ÷ 0.0250 dm³ = 0.0744 mol/dm³.",
        "This uses a 1 : 1 ratio (or halves instead of doubling). Each H₂SO₄ neutralises TWO NaOH.",
        "0.00186 is the number of moles of NaOH — you haven't divided by its volume (0.0250 dm³).",
        "This uses the NaOH volume to find moles of acid (volumes swapped). The acid's moles come from its own titre, 18.60 cm³.",
      ],
      explanation:
        "Moles H₂SO₄ = 0.0500 × (18.60 ÷ 1000) = 0.000930 mol\nRatio H₂SO₄ : NaOH = 1 : 2 → moles NaOH = 0.00186 mol\nConcentration = 0.00186 ÷ 0.0250 = 0.0744 mol/dm³\nSulfuric acid is diprotic (two H⁺ per formula), so it neutralises twice as many OH⁻ as the same moles of HCl or HNO₃.",
      hints: [
        "Start with the solution whose concentration and volume you both know.",
        "Look at the coefficients: 1 H₂SO₄ reacts with how many NaOH?",
        "Divide moles by the volume of NaOH in dm³.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m21",
      topic: "calc",
      section: "calc-moles",
      difficulty: "challenge",
      question: "5.6 g of iron is heated with 4.0 g of sulfur: Fe + S → FeS. Which statement is correct? (Ar: S = 32, Fe = 56)",
      options: [
        "Sulfur is limiting; 11.0 g of FeS forms",
        "Iron is limiting; 8.8 g of FeS forms",
        "Neither is in excess; 9.6 g of FeS forms",
        "Iron is limiting; 9.6 g of FeS forms",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Sulfur has the smaller mass but the larger number of moles (0.125 vs 0.10) — compare moles, not grams.",
        "Fe 0.10 mol, S 0.125 mol, 1 : 1 → iron runs out; 0.10 × 88 = 8.8 g FeS (0.80 g of sulfur is left over).",
        "Adding the masses assumes everything reacts — but there are more moles of S than Fe, so some sulfur is left.",
        "Iron is limiting, but then not all the sulfur reacts, so the product can't weigh the full 9.6 g.",
      ],
      explanation:
        "Moles Fe = 5.6 ÷ 56 = 0.10 mol; moles S = 4.0 ÷ 32 = 0.125 mol.\nRatio 1 : 1, so iron runs out first — iron is limiting, sulfur in excess.\nMoles FeS = 0.10 mol; Mr FeS = 88 → mass = 8.8 g.\nExcess sulfur = 0.025 mol = 0.80 g, and 8.8 + 0.80 = 9.6 g — mass is still conserved.",
      hints: [
        "Never decide the limiting reactant from grams — convert both to moles.",
        "With a 1 : 1 ratio, the smaller number of moles runs out first.",
        "Calculate the product from the limiting reactant only.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m22",
      topic: "calc",
      section: "calc-moles",
      difficulty: "challenge",
      question: "A hydrocarbon contains 85.7% carbon and 14.3% hydrogen by mass. Its relative formula mass is 56. What is its molecular formula? (Ar: H = 1, C = 12)",
      options: ["CH₂", "C₄H₁₀", "C₄H₄", "C₄H₈"],
      answerIndex: 3,
      optionFeedback: [
        "CH₂ is the empirical formula — but its formula mass is 14, not 56, so you still need to scale it up.",
        "C₄H₁₀ is butane, Mr 58, not 56 — don't assume the compound is an alkane.",
        "This comes from dividing by atomic numbers (C = 6) instead of Ar (C = 12), giving a false 1 : 1 ratio.",
        "C 85.7 ÷ 12 = 7.14, H 14.3 ÷ 1 = 14.3 → 1 : 2 → CH₂ (14); 56 ÷ 14 = 4 → C₄H₈.",
      ],
      explanation:
        "C: 85.7 ÷ 12 = 7.14; H: 14.3 ÷ 1 = 14.3\nDivide by the smaller: 1 : 2 → empirical formula CH₂, formula mass 14\nMr ÷ empirical mass = 56 ÷ 14 = 4\nMolecular formula = 4 × CH₂ = C₄H₈ (an alkene, e.g. butene).",
      hints: [
        "Treat the percentages as masses in 100 g and divide by Ar.",
        "Find the empirical formula and its formula mass.",
        "How many empirical units fit into Mr = 56?",
      ],
      strategy: "Follow the method step by step",
    },
    {
      id: "ca-m23",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "challenge",
      question: "Propane burns completely: C₃H₈ + 5O₂ → 3CO₂ + 4H₂O. What volume of oxygen at rtp is needed to burn 11.0 g of propane? (Ar: H = 1, C = 12; molar gas volume = 24 dm³)",
      options: ["30 dm³", "6.0 dm³", "18 dm³", "0.052 dm³"],
      answerIndex: 0,
      optionFeedback: [
        "Moles C₃H₈ = 11.0 ÷ 44 = 0.250; × 5 = 1.25 mol O₂; × 24 = 30 dm³.",
        "This is the volume of the propane itself (0.250 × 24) — you forgot the 1 : 5 ratio.",
        "This uses the 1 : 3 ratio to CO₂ — that's the volume of carbon dioxide produced, not oxygen used.",
        "This divides the moles of oxygen by 24 instead of multiplying (1.25 ÷ 24).",
      ],
      explanation:
        "Mr C₃H₈ = 3 × 12 + 8 × 1 = 44\nMoles C₃H₈ = 11.0 ÷ 44 = 0.250 mol\nRatio C₃H₈ : O₂ = 1 : 5 → 1.25 mol O₂\nVolume O₂ = 1.25 × 24 = 30 dm³\nPick the coefficient of the substance the question actually asks about.",
      hints: [
        "Find moles of propane from its mass.",
        "Which coefficient links propane to OXYGEN?",
        "Moles × 24 gives dm³.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "ca-m24",
      topic: "calc",
      section: "calc-volumes",
      difficulty: "challenge",
      question: "A student needs 250 cm³ of 0.200 mol/dm³ copper(II) sulfate solution and makes it from CuSO₄·5H₂O crystals (Mr = 249.5). What mass of crystals must she weigh out? (Mr of CuSO₄ = 159.5)",
      options: ["7.98 g", "49.9 g", "12.5 g", "31.9 g"],
      answerIndex: 2,
      optionFeedback: [
        "This is right for ANHYDROUS CuSO₄ (0.0500 × 159.5). She is weighing the hydrated crystals, which include the water.",
        "This is the mass for a whole 1 dm³ (0.200 × 249.5) — you forgot to convert 250 cm³ to 0.250 dm³.",
        "Moles = 0.200 × 0.250 = 0.0500 mol; mass = 0.0500 × 249.5 = 12.5 g of crystals.",
        "Two slips at once: a full 1 dm³ AND the anhydrous Mr (0.200 × 159.5).",
      ],
      explanation:
        "Moles CuSO₄ needed = 0.200 × (250 ÷ 1000) = 0.0500 mol\nEach mole of crystals supplies one mole of CuSO₄, and weighs 249.5 g\nMass = 0.0500 × 249.5 = 12.5 g (12.475 g)\nThe water of crystallisation just becomes part of the solvent.",
      hints: [
        "How many moles of CuSO₄ are in 250 cm³ of this solution?",
        "Which Mr belongs to the substance she actually puts on the balance?",
        "Moles × Mr gives the mass.",
      ],
      strategy: "Apply it to a new situation",
    },
  ],
};
