import type { GlossaryCard } from "../../types";

export const glossary: GlossaryCard[] = [
  { topic: "organic", term: "Hydrocarbon", definition: "A compound that contains hydrogen and carbon only.", example: "Methane CH₄, ethene C₂H₄ (ethanol is NOT a hydrocarbon — it contains oxygen)." },
  { topic: "organic", term: "Homologous series", definition: "A family of compounds with the same general formula and the same functional group, similar chemical properties, a gradual trend in physical properties, in which each member differs from the next by CH₂.", example: "Alkanes: CH₄, C₂H₆, C₃H₈ …" },
  { topic: "organic", term: "Functional group", definition: "The atom or group of atoms in a molecule that determines its chemical reactions.", example: "C=C (alkenes), –OH (alcohols), –COOH (carboxylic acids), –COO– (esters)." },
  { topic: "organic", term: "Molecular formula", definition: "The actual number of atoms of each element in one molecule of a compound.", example: "Butane: C₄H₁₀." },
  { topic: "organic", term: "Empirical formula", definition: "The simplest whole-number ratio of atoms of each element in a compound.", example: "Butane C₄H₁₀ → C₂H₅; every alkene → CH₂." },
  { topic: "organic", term: "General formula", definition: "An algebraic formula that fits every member of a homologous series.", example: "Alkanes CₙH₂ₙ₊₂; alkenes CₙH₂ₙ; alcohols CₙH₂ₙ₊₁OH." },
  { topic: "organic", term: "Displayed formula", definition: "A formula that shows every atom and every covalent bond in a molecule.", example: "Draw all C–H, C–C, C=C and O–H bonds as lines." },
  { topic: "organic", term: "Structural isomers", definition: "Compounds with the same molecular formula but different structural (displayed) formulae.", example: "Butane and methylpropane (C₄H₁₀); propan-1-ol and propan-2-ol." },
  { topic: "organic", term: "Saturated", definition: "Containing only single carbon–carbon bonds (no C=C double bonds).", example: "Alkanes are saturated hydrocarbons." },
  { topic: "organic", term: "Unsaturated", definition: "Containing at least one carbon–carbon double bond (C=C).", example: "Alkenes — they decolourise bromine water." },
  { topic: "organic", term: "Fraction", definition: "A mixture of hydrocarbons with similar chain lengths and similar boiling points, collected from fractional distillation of crude oil.", example: "Refinery gases, gasoline, kerosene, diesel, fuel oil, bitumen." },
  { topic: "organic", term: "Fractional distillation (of crude oil)", definition: "Separating crude oil by heating it to vapour in a column with a temperature gradient (hot at the bottom, cool at the top); each fraction condenses at the level where the temperature is below its boiling point." },
  { topic: "organic", term: "Incomplete combustion", definition: "Burning a fuel in a limited supply of oxygen, producing carbon monoxide and/or carbon (soot) as well as water.", example: "2CH₄ + 3O₂ → 2CO + 4H₂O. CO combines with haemoglobin, so the blood carries less oxygen." },
  { topic: "organic", term: "Cracking", definition: "Breaking long-chain alkanes into shorter alkanes and alkenes using a silica or alumina catalyst at about 600–700 °C.", example: "C₁₀H₂₂ → C₈H₁₈ + C₂H₄" },
  { topic: "organic", term: "Substitution reaction", definition: "A reaction in which one atom or group in a molecule is replaced by another atom or group.", example: "CH₄ + Br₂ → CH₃Br + HBr (in UV light)." },
  { topic: "organic", term: "Addition reaction", definition: "A reaction in which two molecules join to form a single product; for alkenes the C=C double bond opens.", example: "C₂H₄ + Br₂ → C₂H₄Br₂" },
  { topic: "organic", term: "Test for an alkene", definition: "Shake with bromine water: it turns from orange to colourless. An alkane leaves it orange.", example: "Never write \"clear\" — write colourless." },
  { topic: "organic", term: "Fermentation", definition: "Conversion of glucose into ethanol and carbon dioxide by yeast at about 30 °C under anaerobic conditions.", example: "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂" },
  { topic: "organic", term: "Hydration of ethene", definition: "Addition of steam to ethene to make ethanol, at 300 °C and 60–70 atm with a phosphoric acid catalyst.", example: "C₂H₄ + H₂O ⇌ C₂H₅OH" },
  { topic: "organic", term: "Dehydration (of ethanol)", definition: "Removal of water from ethanol to form ethene by passing ethanol vapour over hot aluminium oxide.", example: "C₂H₅OH → C₂H₄ + H₂O" },
  { topic: "organic", term: "Carboxylic acid", definition: "A compound containing the –COOH functional group; a weak acid that is only partially ionised in water.", example: "Ethanoic acid CH₃COOH (vinegar)." },
  { topic: "organic", term: "Ester", definition: "A compound containing the –COO– functional group, formed when a carboxylic acid reacts with an alcohol (concentrated sulfuric acid catalyst); water is also produced.", example: "Ethyl ethanoate CH₃COOC₂H₅ — used in flavourings and perfumes." },
  { topic: "organic", term: "Addition polymerisation", definition: "Many monomers containing a C=C double bond join together to form a long-chain polymer as the only product.", example: "n CH₂=CH₂ → –[CH₂–CH₂]ₙ– (poly(ethene))." },
  { topic: "organic", term: "Condensation polymerisation", definition: "Monomers with two functional groups join together, eliminating a small molecule such as water each time a link forms.", example: "Dicarboxylic acid + diol → polyester + water." },
  { topic: "organic", term: "Biodegradable", definition: "Able to be broken down by microorganisms (bacteria) in the environment.", example: "Biopolyesters are biodegradable; poly(ethene) is not." },
];
