import type { MCQ, QuestionSet } from "../../types";

export const mcq: QuestionSet<MCQ> = {
  id: "mcq-organic",
  title: "Multiple choice · Organic Chemistry",
  subtitle: "Naming, crude oil, alkanes & alkenes, alcohols, acids & esters, polymers",
  topic: "organic",
  questions: [
    {
      id: "or-m01",
      topic: "organic",
      section: "organic-intro",
      difficulty: "warmup",
      question: "Which of these is the correct definition of a hydrocarbon?",
      options: [
        "A compound containing carbon, hydrogen and oxygen",
        "A substance that burns to form carbon dioxide and water",
        "A compound containing hydrogen and carbon only",
        "A mixture of compounds obtained from crude oil",
      ],
      answerIndex: 2,
      optionFeedback: [
        "This describes alcohols, acids and sugars. A hydrocarbon contains no oxygen at all.",
        "Hydrocarbons do burn this way, but so do ethanol and glucose, which are not hydrocarbons. This is a property, not the definition.",
        "Only hydrogen and carbon atoms are present — the word \"only\" is the mark-earning part of the definition.",
        "Crude oil is a mixture OF hydrocarbons; a single hydrocarbon is a compound, not a mixture.",
      ],
      explanation:
        "A hydrocarbon is a compound made of hydrogen and carbon atoms only. Methane, ethene and octane are hydrocarbons; ethanol (C₂H₅OH) is not, because it contains oxygen. In exams, \"carbon and hydrogen\" without \"only\" usually loses the mark.",
      hints: ["Think about which elements are named in the word itself: hydro-carbon."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m02",
      topic: "organic",
      section: "organic-crude",
      difficulty: "warmup",
      question: "Which crude oil fraction has the highest boiling point?",
      options: ["bitumen", "refinery gases", "kerosene", "gasoline"],
      answerIndex: 0,
      optionFeedback: [
        "Bitumen has the longest molecules and the strongest intermolecular forces, so it has the highest boiling point and is collected at the bottom of the column.",
        "Refinery gases have the shortest molecules and the LOWEST boiling points — they leave from the top of the column.",
        "Kerosene is in the middle of the column; diesel, fuel oil and bitumen all boil at higher temperatures.",
        "Gasoline is near the top of the column, with low boiling points; it is the opposite end from the right answer.",
      ],
      explanation:
        "Going down the fractionating column the molecules get longer, so the intermolecular forces get stronger and the boiling point rises. Order from top: refinery gases, gasoline, kerosene, diesel, fuel oil, bitumen. Bitumen is so involatile that it drains from the bottom as a thick liquid.",
      hints: ["The fraction with the highest boiling point is collected where the column is hottest."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m03",
      topic: "organic",
      section: "organic-hydrocarbons",
      difficulty: "warmup",
      question: "A few drops of bromine water are shaken with an alkene. What colour change is seen?",
      options: ["colourless to orange", "orange to clear", "orange to green", "orange to colourless"],
      answerIndex: 3,
      optionFeedback: [
        "This is the reverse. Bromine water starts orange; the alkene uses up the bromine.",
        "Tempting, but \"clear\" means transparent — orange bromine water is already clear. Mark schemes reject \"clear\"; the word needed is colourless.",
        "Orange to green is the colour change for acidified potassium dichromate(VI) oxidising an alcohol, not for the alkene test.",
        "Bromine adds across the C=C double bond, so the orange bromine is used up and the solution is decolourised.",
      ],
      explanation:
        "Alkenes contain a C=C double bond, so bromine adds across it (an addition reaction). The orange colour of the bromine disappears: orange to colourless. Alkanes have no C=C, so the bromine water stays orange.",
      hints: ["The bromine is being used up in an addition reaction — what happens to its colour?"],
      strategy: "Recall the definition",
    },
    {
      id: "or-m04",
      topic: "organic",
      section: "organic-alcohols",
      difficulty: "warmup",
      question: "Which conditions are used to make ethanol by fermentation?",
      options: [
        "steam, 300 °C, phosphoric acid catalyst",
        "yeast, about 30 °C, no oxygen present",
        "yeast, about 80 °C, plenty of air",
        "hot aluminium oxide catalyst",
      ],
      answerIndex: 1,
      optionFeedback: [
        "These are the conditions for hydration of ethene, the other industrial method of making ethanol.",
        "Yeast enzymes work best at about 30 °C, and air must be kept out so the ethanol is not oxidised to ethanoic acid.",
        "80 °C would denature the yeast's enzymes, and air would let the ethanol be oxidised to ethanoic acid.",
        "Hot aluminium oxide is used to DEHYDRATE ethanol to ethene — the reverse direction.",
      ],
      explanation:
        "Fermentation: glucose solution + yeast at about 30 °C under anaerobic conditions. C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. Too hot denatures the enzymes; oxygen would let microbes oxidise the ethanol to ethanoic acid.",
      hints: ["Fermentation uses a living organism — what temperature and atmosphere would it need?"],
      strategy: "Recall the definition",
    },
    {
      id: "or-m05",
      topic: "organic",
      section: "organic-acids-esters",
      difficulty: "warmup",
      question: "Ethanol reacts with ethanoic acid in the presence of concentrated sulfuric acid. What is the name of the ester formed?",
      options: ["ethanoyl ethanol", "methyl ethanoate", "ethanol ethanoate", "ethyl ethanoate"],
      answerIndex: 3,
      optionFeedback: [
        "Not a correct ester name. Esters are named alkyl-group (from the alcohol) then -oate (from the acid).",
        "Methyl would come from methanol. Here the alcohol is ethanol, which gives the ethyl part.",
        "Close, but the alcohol part is named as an alkyl group (ethyl), not as the alcohol (ethanol).",
        "Ethanol gives the ethyl part (first) and ethanoic acid gives the ethanoate part (second).",
      ],
      explanation:
        "Ester names have two parts: the alcohol becomes an alkyl group (-yl) written first, and the acid becomes -oate written second. Ethanol + ethanoic acid → ethyl ethanoate (CH₃COOC₂H₅) + water.",
      hints: ["Change the alcohol's ending to -yl and the acid's ending to -oate."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m06",
      topic: "organic",
      section: "organic-polymers",
      difficulty: "warmup",
      question: "What is the monomer used to make PVC, poly(chloroethene)?",
      options: ["CH₂=CHCl", "CH₃CH₂Cl", "CF₂=CF₂", "CH₂=CHCH₃"],
      answerIndex: 0,
      optionFeedback: [
        "Chloroethene has the C=C needed for addition polymerisation and the Cl atom that appears in every repeat unit.",
        "Chloroethane has no C=C double bond, so it cannot undergo addition polymerisation.",
        "Tetrafluoroethene is the monomer for PTFE (non-stick coatings), not PVC.",
        "Propene is the monomer for poly(propene); it has a CH₃ group, not a Cl atom.",
      ],
      explanation:
        "Addition polymers are named poly(monomer). Poly(chloroethene) is made from chloroethene, CH₂=CHCl. The C=C opens and the repeat unit is –[CH₂–CHCl]–.",
      hints: ["The polymer's name contains the monomer's name in brackets — and the monomer must have a C=C."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m07",
      topic: "organic",
      section: "organic-intro",
      difficulty: "core",
      question: "What is the empirical formula of hexane, C₆H₁₄?",
      options: ["C₆H₁₄", "C₃H₇", "CH₂", "CH₃"],
      answerIndex: 1,
      optionFeedback: [
        "This is the molecular formula. 6 and 14 have a common factor of 2, so it can be simplified.",
        "Dividing C₆H₁₄ by the highest common factor, 2, gives the simplest whole-number ratio C₃H₇.",
        "CH₂ is the empirical formula of every ALKENE (CₙH₂ₙ). Hexane is an alkane, CₙH₂ₙ₊₂.",
        "C:H = 1:3 is the empirical formula of ethane (C₂H₆), not hexane. 14 ÷ 6 is not 3.",
      ],
      explanation:
        "The empirical formula is the simplest whole-number ratio of atoms. For C₆H₁₄ the highest common factor of 6 and 14 is 2, so the empirical formula is C₃H₇. Odd-carbon alkanes such as pentane C₅H₁₂ already have the simplest ratio.",
      hints: ["Find the largest number that divides into both 6 and 14.", "Divide both subscripts by it — keep whole numbers."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m08",
      topic: "organic",
      section: "organic-intro",
      difficulty: "core",
      question: "Which statement about the members of a homologous series is NOT correct?",
      options: [
        "They have the same general formula.",
        "Each member differs from the next by CH₂.",
        "They have identical boiling points.",
        "They have similar chemical properties.",
      ],
      answerIndex: 2,
      optionFeedback: [
        "This IS a feature — e.g. all alkanes fit CₙH₂ₙ₊₂ — so it is not the statement you want.",
        "This IS a feature — successive members differ by one CH₂ unit.",
        "Boiling points show a GRADUAL CHANGE (a trend) as the chain gets longer; they are not identical.",
        "This IS a feature — the same functional group gives similar chemical reactions.",
      ],
      explanation:
        "A homologous series has the same general formula, the same functional group, similar chemical properties, a gradation (trend) in physical properties such as boiling point, and each member differs by CH₂. Boiling point rises with chain length because intermolecular forces get stronger.",
      hints: ["Remember the five features of a homologous series.", "Physical properties change gradually along the series — they are not the same."],
      strategy: "Eliminate wrong options",
    },
    {
      id: "or-m09",
      topic: "organic",
      section: "organic-intro",
      difficulty: "core",
      question: "How many structural isomers have the molecular formula C₅H₁₂?",
      options: ["2", "4", "5", "3"],
      answerIndex: 3,
      optionFeedback: [
        "Two is the number for C₄H₁₀ (butane and methylpropane). C₅H₁₂ has one more.",
        "Drawing four usually means one is the same molecule bent or flipped — check whether each has a different longest chain or branch position.",
        "Five would be the number of carbon atoms, not the number of isomers.",
        "Pentane plus two branched isomers (stretch names: 2-methylbutane and 2,2-dimethylpropane) — three different arrangements.",
      ],
      explanation:
        "C₅H₁₂ has three structural isomers: pentane (straight chain), one with a single branch and one with two branches on the middle carbon (stretch names: 2-methylbutane and 2,2-dimethylpropane — you only need to draw them). Moving a branch to the other end or bending the chain does not make a new isomer — it is the same molecule.",
      hints: ["Start with the straight chain, then shorten the main chain by one carbon and add branches.", "Check every drawing's longest chain — a bent chain is not a new compound."],
      strategy: "Consider the extremes",
    },
    {
      id: "or-m10",
      topic: "organic",
      section: "organic-intro",
      difficulty: "core",
      question: "Which pair of compounds are structural isomers of each other?",
      options: ["butane and methylpropane", "propane and propene", "ethanol and ethanoic acid", "butane and but-1-ene"],
      answerIndex: 0,
      optionFeedback: [
        "Both are C₄H₁₀ — same molecular formula, but one chain is straight and the other branched.",
        "Propane is C₃H₈ and propene is C₃H₆ — different molecular formulae, so not isomers.",
        "Ethanol is C₂H₆O and ethanoic acid is C₂H₄O₂ — different molecular formulae.",
        "Butane is C₄H₁₀ and but-1-ene is C₄H₈ — they have different numbers of hydrogen atoms.",
      ],
      explanation:
        "Structural isomers have the same molecular formula but different structural formulae. Always check the molecular formula first: only butane and methylpropane are both C₄H₁₀. (Naming branched isomers such as methylpropane is stretch — the key skill is spotting the same molecular formula.) Same number of carbons is not enough.",
      hints: ["Write the molecular formula of each compound.", "Isomers must have exactly the same number of every type of atom."],
      strategy: "Compare and contrast",
    },
    {
      id: "or-m11",
      topic: "organic",
      section: "organic-crude",
      difficulty: "core",
      question: "Why is carbon monoxide from incomplete combustion dangerous to humans?",
      options: [
        "It dissolves in moisture in the lungs to form an acid",
        "It is a greenhouse gas that causes global warming",
        "It combines with haemoglobin, so less oxygen is carried",
        "It reacts with oxygen in the blood to form carbon dioxide",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Carbon monoxide is a neutral oxide — it is SO₂ and NOₓ that dissolve to form acids (acid rain).",
        "That describes carbon dioxide (and methane). It does not explain why CO is toxic to a person in a room.",
        "CO binds to haemoglobin in red blood cells, reducing the amount of oxygen the blood can carry — this can be fatal.",
        "Sounds plausible, but CO does not react with oxygen in the blood; it blocks haemoglobin so oxygen cannot be carried.",
      ],
      explanation:
        "Carbon monoxide is toxic because it combines with haemoglobin in red blood cells, reducing the blood's capacity to carry oxygen. It is colourless and odourless, so it cannot be detected without an alarm. A mark scheme needs both haemoglobin AND less oxygen carried.",
      hints: ["Think about how the blood carries oxygen around the body.", "Which molecule in red blood cells does CO attach to?"],
      strategy: "Recall the definition",
    },
    {
      id: "or-m12",
      topic: "organic",
      section: "organic-crude",
      difficulty: "core",
      question: "Car engines release oxides of nitrogen. Where does the nitrogen in these oxides come from?",
      options: [
        "Nitrogen impurities in the fuel burning in oxygen",
        "Nitrogen gas in the air, reacting with oxygen in the hot engine",
        "Nitrogen formed when the hydrocarbons are cracked",
        "Ammonia added to petrol to help it burn smoothly",
      ],
      answerIndex: 1,
      optionFeedback: [
        "This is the source of SULFUR dioxide (sulfur impurities). The nitrogen comes from somewhere else.",
        "The very high temperature in the engine lets N₂ and O₂ from the air react to form NO and NO₂.",
        "Hydrocarbons contain only carbon and hydrogen, so cracking them cannot produce nitrogen.",
        "Ammonia is not added to petrol; this is invented — the nitrogen comes from the air drawn into the engine.",
      ],
      explanation:
        "Air is about 78% nitrogen. Normally N₂ is unreactive, but at the very high temperatures in an engine it reacts with oxygen: N₂ + O₂ → 2NO, and NO is oxidised further to NO₂. Oxides of nitrogen dissolve in rain to form acid rain, like SO₂.",
      hints: ["Petrol is a mixture of hydrocarbons — does it contain nitrogen?", "What else enters the engine besides fuel?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "or-m13",
      topic: "organic",
      section: "organic-crude",
      difficulty: "core",
      question: "Which conditions are used for the catalytic cracking of long-chain alkanes?",
      options: [
        "silica or alumina catalyst at 600–700 °C",
        "iron catalyst at 450 °C and 200 atm",
        "phosphoric acid catalyst at 300 °C and 60 atm",
        "nickel catalyst at 150 °C with hydrogen",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Vaporised alkanes are passed over hot silica or alumina, which catalyses the breaking of C–C bonds.",
        "These are the Haber process conditions for making ammonia.",
        "These are the conditions for hydration of ethene to make ethanol.",
        "A nickel catalyst with hydrogen is used to ADD hydrogen to alkenes — the opposite of breaking molecules up.",
      ],
      explanation:
        "Catalytic cracking uses a silica or alumina catalyst at about 600–700 °C. The long-chain alkane breaks into a shorter alkane and at least one alkene. Learn each process's conditions separately — examiners like to mix them up.",
      hints: ["Cracking needs a high temperature to break strong C–C bonds.", "The catalyst is an oxide of silicon or aluminium."],
      strategy: "Eliminate wrong options",
    },
    {
      id: "or-m14",
      topic: "organic",
      section: "organic-hydrocarbons",
      difficulty: "core",
      question: "Methane reacts with bromine in ultraviolet light. What are the products when one molecule of each reacts?",
      options: ["CH₂Br₂ and H₂", "CH₄Br₂ only", "CH₃Br and H₂", "CH₃Br and HBr"],
      answerIndex: 3,
      optionFeedback: [
        "Two H atoms have been replaced and released as H₂ — but in substitution each replaced H leaves with a Br as HBr.",
        "This would be addition, but methane is saturated: carbon cannot form more than four bonds.",
        "The Br count doesn't balance: one Br atom has gone missing. The replaced H atom joins the other Br as HBr.",
        "One H is substituted by Br to give bromomethane, and the displaced H combines with the other Br atom to form HBr.",
      ],
      explanation:
        "Alkanes undergo substitution with bromine in UV light: CH₄ + Br₂ → CH₃Br + HBr. One Br atom replaces an H atom; the other Br atom joins with that H to form hydrogen bromide. UV light supplies the energy to break the Br–Br bond.",
      hints: ["In substitution, one atom swaps places with another.", "Count the Br atoms on each side — both must end up somewhere."],
      strategy: "Balance the equation",
    },
    {
      id: "or-m15",
      topic: "organic",
      section: "organic-hydrocarbons",
      difficulty: "core",
      question: "Which formula is the formula of an alkene?",
      options: ["C₆H₁₄", "C₅H₁₀", "C₂H₆", "C₄H₁₀"],
      answerIndex: 1,
      optionFeedback: [
        "C₆H₁₄ fits CₙH₂ₙ₊₂ (n = 6) — it is hexane, an alkane.",
        "C₅H₁₀ fits CₙH₂ₙ (n = 5, 2n = 10) — pentene, an alkene.",
        "C₂H₆ fits CₙH₂ₙ₊₂ — ethane, an alkane. Ethene is C₂H₄.",
        "C₄H₁₀ fits CₙH₂ₙ₊₂ — butane, an alkane. Butene is C₄H₈.",
      ],
      explanation:
        "Alkenes have the general formula CₙH₂ₙ: the number of H atoms is exactly twice the number of C atoms. Alkanes have two more H atoms (CₙH₂ₙ₊₂) because they have no C=C. Test each option: is H = 2 × C?",
      hints: ["Recall the general formula of the alkenes.", "Check each option: is the number of H atoms exactly double the number of C atoms?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "or-m16",
      topic: "organic",
      section: "organic-alcohols",
      difficulty: "core",
      question: "How can ethanol be converted into ethene in the laboratory?",
      options: [
        "warming it with yeast at 30 °C",
        "heating it with acidified potassium dichromate(VI)",
        "passing its vapour over hot aluminium oxide",
        "passing it over a silica catalyst at 650 °C",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Yeast at 30 °C MAKES ethanol from glucose by fermentation; it does not turn ethanol into ethene.",
        "Acidified dichromate(VI) OXIDISES ethanol to ethanoic acid (orange → green).",
        "Hot aluminium oxide catalyses dehydration: C₂H₅OH → C₂H₄ + H₂O.",
        "Silica at 650 °C is used for cracking long-chain alkanes, not for dehydrating ethanol.",
      ],
      explanation:
        "Dehydration removes water from ethanol: C₂H₅OH → C₂H₄ + H₂O. Ethanol vapour is passed over heated aluminium oxide, which acts as a catalyst. It is the reverse of hydration of ethene and gives a renewable source of ethene.",
      hints: ["Ethanol → ethene means a molecule of water must be removed.", "Which catalyst is used for dehydration?"],
      strategy: "Compare and contrast",
    },
    {
      id: "or-m17",
      topic: "organic",
      section: "organic-alcohols",
      difficulty: "core",
      question: "Ethanol is heated with acidified potassium dichromate(VI). What colour change is seen in the mixture?",
      options: ["orange to green", "orange to colourless", "green to orange", "purple to colourless"],
      answerIndex: 0,
      optionFeedback: [
        "The orange dichromate(VI) ions are reduced to green chromium(III) ions as the ethanol is oxidised to ethanoic acid.",
        "That is the bromine water test for an alkene — a different reagent and a different reaction.",
        "This is the right two colours in the wrong order: dichromate(VI) starts orange.",
        "Purple to colourless is the colour change of potassium manganate(VII), not dichromate(VI).",
      ],
      explanation:
        "Acidified potassium dichromate(VI) is an oxidising agent. It oxidises ethanol to ethanoic acid (C₂H₅OH + 2[O] → CH₃COOH + H₂O) and is itself reduced, changing from orange to green. Don't confuse it with bromine water (orange → colourless).",
      hints: ["Potassium dichromate(VI) solution is orange to start with.", "When it is reduced, it forms chromium(III), which is green."],
      strategy: "Recall the definition",
    },
    {
      id: "or-m18",
      topic: "organic",
      section: "organic-acids-esters",
      difficulty: "core",
      question: "Ethanoic acid reacts with sodium carbonate solution. Which are the products?",
      options: [
        "sodium ethanoate, water and hydrogen",
        "sodium ethanoate and water only",
        "ethyl ethanoate, hydrogen and carbon dioxide",
        "sodium ethanoate, water and carbon dioxide",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Hydrogen is made when an acid reacts with a METAL. A carbonate gives carbon dioxide.",
        "Salt + water only is what an acid gives with an alkali or a metal oxide. The carbonate also releases CO₂ (fizzing).",
        "An ester is made from an acid and an ALCOHOL, not from a carbonate.",
        "Acid + carbonate → salt + water + carbon dioxide: 2CH₃COOH + Na₂CO₃ → 2CH₃COONa + H₂O + CO₂.",
      ],
      explanation:
        "Carboxylic acids are weak acids but still show typical acid reactions. With a carbonate: salt + water + carbon dioxide. The salt of ethanoic acid is an ethanoate, so sodium ethanoate forms. You would see fizzing; the gas turns limewater milky.",
      hints: ["What are the products when any acid reacts with a carbonate?", "Salts of ethanoic acid are called ethanoates."],
      strategy: "Apply it to a new situation",
    },
    {
      id: "or-m19",
      topic: "organic",
      section: "organic-crude",
      difficulty: "challenge",
      question: "Hexadecane is cracked: C₁₆H₃₄ → C₁₀H₂₂ + 3X. What is the formula of X?",
      options: ["C₃H₆", "C₆H₁₂", "C₂H₄", "C₂H₆"],
      answerIndex: 2,
      optionFeedback: [
        "C₃H₆ × 3 would be C₉H₁₈ — too many atoms. Check the carbon count: 16 − 10 = 6, shared between 3 molecules.",
        "C₆H₁₂ is the TOTAL left over. This is what you get if you forget to divide by 3 for the three molecules of X.",
        "Atoms left: C 16 − 10 = 6, H 34 − 22 = 12, so C₆H₁₂ ÷ 3 = C₂H₄ (ethene).",
        "C₂H₆ × 3 = C₆H₁₈ — six H atoms too many. A cracking product with C₂ alongside an alkane must be ethene.",
      ],
      explanation:
        "Balance by subtraction then share out:\n- C: 16 − 10 = 6; H: 34 − 22 = 12 → 3X = C₆H₁₂\n- X = C₂H₄ (ethene)\nC₁₀H₂₂ is decane (an alkane, CₙH₂ₙ₊₂) and X is an alkene — cracking always gives at least one alkene, because there are not enough H atoms for every product to be an alkane.",
      hints: ["Work out how many C and H atoms are left after making C₁₀H₂₂.", "Those atoms are shared between three identical molecules.", "Check your answer fits CₙH₂ₙ."],
      strategy: "Balance the equation",
    },
    {
      id: "or-m20",
      topic: "organic",
      section: "organic-hydrocarbons",
      difficulty: "challenge",
      question: "What is the maximum mass of bromine that reacts with 2.8 g of ethene? (Ar: C = 12, H = 1, Br = 80)",
      options: ["8.0 g", "16 g", "32 g", "1.6 g"],
      answerIndex: 1,
      optionFeedback: [
        "This is what you get if you use Ar of Br (80) instead of Mr of Br₂ (160). Bromine exists as Br₂ molecules.",
        "0.10 mol C₂H₄ reacts with 0.10 mol Br₂ (1:1 addition); 0.10 × 160 = 16 g.",
        "This doubles the correct answer — as if two Br₂ molecules added to each C=C. One C=C adds one Br₂.",
        "This is ten times too small — the slip of using 16 instead of 160 for the Mr of Br₂.",
      ],
      explanation:
        "C₂H₄ + Br₂ → C₂H₄Br₂ (1 : 1).\n- Mr C₂H₄ = 2 × 12 + 4 × 1 = 28; moles = 2.8 ÷ 28 = 0.10 mol\n- moles Br₂ = 0.10 mol; Mr Br₂ = 2 × 80 = 160\n- mass = 0.10 × 160 = 16 g",
      hints: ["Write the balanced equation for the addition reaction.", "Find the moles of ethene using its Mr.", "Bromine is diatomic — what is the Mr of Br₂?"],
      strategy: "Use the mole ratio",
    },
    {
      id: "or-m21",
      topic: "organic",
      section: "organic-alcohols",
      difficulty: "challenge",
      question: "Which is an advantage of making ethanol by hydration of ethene rather than by fermentation?",
      options: [
        "It uses a renewable raw material from crops",
        "It runs at a lower temperature, so it saves energy",
        "It produces carbon dioxide that can be sold",
        "It is continuous and gives purer ethanol",
      ],
      answerIndex: 3,
      optionFeedback: [
        "This is an advantage of FERMENTATION. Ethene comes from cracking crude oil, which is non-renewable.",
        "The reverse is true: hydration needs 300 °C and 60–70 atm, whereas fermentation runs at about 30 °C.",
        "Hydration is an addition reaction — ethanol is the only product. Fermentation is the method that makes CO₂.",
        "Hydration runs continuously, is fast, and gives almost pure ethanol; fermentation is a slow batch process giving dilute, impure ethanol.",
      ],
      explanation:
        "Hydration (C₂H₄ + H₂O ⇌ C₂H₅OH; 300 °C, 60–70 atm, phosphoric acid) is fast, continuous and gives pure ethanol. Fermentation is renewable and low-temperature, but slow, batch and produces impure ethanol that needs distilling. Always say which method each point favours.",
      hints: ["Hydration uses ethene from crude oil at 300 °C and 60–70 atm.", "Eliminate any statement that is really an advantage of fermentation.", "Think about rate, purity and batch versus continuous."],
      strategy: "Compare and contrast",
    },
    {
      id: "or-m22",
      topic: "organic",
      section: "organic-acids-esters",
      difficulty: "challenge",
      question: "Which is the structural formula of methyl propanoate?",
      options: ["CH₃CH₂COOCH₃", "CH₃COOCH₂CH₃", "HCOOCH₂CH₂CH₃", "CH₃COOCH₃"],
      answerIndex: 0,
      optionFeedback: [
        "The acid part CH₃CH₂COO– (three carbons, propanoate) is written first, joined to the methyl group from methanol.",
        "This is ethyl ethanoate — an isomer of methyl propanoate (both C₄H₈O₂), but made from ethanol + ethanoic acid.",
        "This is propyl methanoate — the acid part HCOO– has only one carbon (methanoate).",
        "This is methyl ethanoate — the acid part CH₃COO– has only two carbons.",
      ],
      explanation:
        "Methyl propanoate comes from methanol + propanoic acid (CH₃CH₂COOH). In the formula, the acid part is written first: CH₃CH₂COO–, then the alkyl group from the alcohol: –CH₃. So CH₃CH₂COOCH₃. Note the name puts the alcohol part first but the formula puts the acid part first.",
      hints: ["Which alcohol and which acid make methyl propanoate?", "Count the carbons in the part attached to the C=O: that is the acid part.", "Propanoate has three carbons including the C of COO."],
      strategy: "Work backwards",
    },
    {
      id: "or-m23",
      topic: "organic",
      section: "organic-polymers",
      difficulty: "challenge",
      question: "The diagram shows the repeat unit of an addition polymer. Which is the monomer?",
      diagram: `<svg viewBox="0 0 210 125" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Repeat unit of a polymer: two carbons joined by a single bond in brackets; the left carbon has H and CH3, the right carbon has H and Cl"><line x1="36" y1="60" x2="71" y2="60" stroke="#334155" stroke-width="1.6"/><line x1="139" y1="60" x2="174" y2="60" stroke="#334155" stroke-width="1.6"/><line x1="90.0" y1="60.0" x2="120.0" y2="60.0" stroke="#334155" stroke-width="1.6"/><line x1="80.0" y1="50.0" x2="80.0" y2="35.0" stroke="#334155" stroke-width="1.6"/><line x1="80.0" y1="70.0" x2="80.0" y2="87.0" stroke="#334155" stroke-width="1.6"/><line x1="130.0" y1="50.0" x2="130.0" y2="35.0" stroke="#334155" stroke-width="1.6"/><line x1="130.0" y1="70.0" x2="130.0" y2="87.0" stroke="#334155" stroke-width="1.6"/><text x="80" y="60" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#0f172a">C</text><text x="130" y="60" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#0f172a">C</text><text x="80" y="25" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#0f172a">H</text><text x="80" y="97" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#0f172a">CH₃</text><text x="130" y="25" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#0f172a">H</text><text x="130" y="97" text-anchor="middle" dominant-baseline="central" font-size="14" font-family="sans-serif" fill="#15803d">Cl</text><path d="M56,16 h-8 v90 h8" fill="none" stroke="#0f172a" stroke-width="1.8"/><path d="M154,16 h8 v90 h-8" fill="none" stroke="#0f172a" stroke-width="1.8"/><text x="172" y="112" font-size="15" font-family="sans-serif" fill="#0f172a">n</text></svg>`,
      options: ["CH₃CH₂CH₂Cl", "CH₃CH=CHCl", "CH₂=CHCl", "CH₂=C(CH₃)Cl"],
      answerIndex: 1,
      optionFeedback: [
        "This has no C=C double bond, so it cannot form an addition polymer.",
        "Put a C=C between the two main-chain carbons and keep their groups: CH₃ and H on one, Cl and H on the other.",
        "Chloroethene gives –[CH₂–CHCl]–; it has no CH₃ group, which the repeat unit does.",
        "This puts CH₃ and Cl on the SAME carbon; its repeat unit would be –[CH₂–C(CH₃)Cl]–.",
      ],
      explanation:
        "To find the monomer, take the two carbons in the main chain, remove the extension bonds and draw a C=C between them, keeping the side groups where they are. One carbon carries H and CH₃, the other H and Cl, so the monomer is CH₃CH=CHCl (1-chloropropene).",
      hints: ["Addition polymers come from monomers with a C=C.", "Look at which groups are on EACH main-chain carbon.", "Keep each side group on the same carbon when you rebuild the double bond."],
      strategy: "Work backwards",
    },
    {
      id: "or-m24",
      topic: "organic",
      section: "organic-polymers",
      difficulty: "challenge",
      question: "Which pair of monomers could react together to form a polyester by condensation polymerisation?",
      options: [
        "HOCH₂CH₂OH and HOCH₂CH₂CH₂OH",
        "CH₃COOH and CH₃CH₂OH",
        "HOOCCH₂COOH and HOCH₂CH₂OH",
        "HOOCCH₂COOH and CH₃CH₂OH",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Two diols have –OH groups only; an ester link needs a –COOH group to react with an –OH group.",
        "Each molecule has only one functional group, so they form one small ester (ethyl ethanoate) and the chain cannot grow.",
        "A dicarboxylic acid and a diol each have two reactive groups, so ester links can form at both ends and the chain keeps growing, eliminating water.",
        "Ethanol has only one –OH group, so it caps each end of the acid and the chain stops after one link at each end.",
      ],
      explanation:
        "A polyester forms from a dicarboxylic acid (–COOH at both ends) and a diol (–OH at both ends). Each –COOH reacts with an –OH to form an ester link (–COO–), eliminating a water molecule. Because both monomers have two functional groups, the chain can keep growing in both directions.",
      hints: ["An ester link forms between –COOH and –OH.", "To make a long chain, each monomer must be able to react at BOTH ends.", "Count the functional groups on each monomer."],
      strategy: "Apply it to a new situation",
    },
    {
      id: "or-m25",
      topic: "organic",
      section: "organic-intro",
      difficulty: "core",
      question: "Two unbranched alkenes both have the molecular formula C₄H₈. One is CH₂=CHCH₂CH₃. What is the name of the other one, CH₃CH=CHCH₃?",
      options: ["but-1-ene", "but-3-ene", "but-2-ene", "butane"],
      answerIndex: 2,
      optionFeedback: [
        "But-1-ene is CH₂=CHCH₂CH₃, where the C=C starts at carbon 1 — that is the first molecule.",
        "There is no but-3-ene: you always number from the end that gives the lowest number, and here the C=C starts at carbon 2 counting from either end.",
        "The C=C double bond is between carbons 2 and 3 of the straight four-carbon chain, so it is but-2-ene.",
        "Butane is the ALKANE C₄H₁₀ with no double bond — it has two more hydrogen atoms.",
      ],
      explanation:
        "'But' = 4 carbons; '-ene' = C=C double bond. The number tells you which carbon the double bond starts on, counting from the end that gives the lowest number. In CH₃CH=CHCH₃ the double bond is between C2 and C3, so it is but-2-ene. But-1-ene and but-2-ene are unbranched-chain structural isomers: same molecular formula C₄H₈, different position of the C=C.",
      hints: ["Number the carbon atoms along the chain.", "On which carbon does the double bond start? Count from whichever end gives the lower number."],
      strategy: "Apply it to a new situation",
    },
    {
      id: "or-m26",
      topic: "organic",
      section: "organic-polymers",
      difficulty: "core",
      question: "PTFE, used for non-stick coatings, is the addition polymer poly(tetrafluoroethene). Which is the repeat unit of PTFE?",
      options: [
        "–[CF₂–CF₂]– with a double bond between the carbons",
        "–[CH₂–CHF]–",
        "–[CF₂–CF₂]– with a single bond between the carbons",
        "–[CH₂–CH₂]– with four F atoms attached to each carbon",
      ],
      answerIndex: 2,
      optionFeedback: [
        "The monomer CF₂=CF₂ has a double bond, but in the polymer the C=C opens up to make new bonds to the neighbouring units — the repeat unit has a C–C single bond.",
        "This has only one fluorine. 'Tetra' means four: the monomer CF₂=CF₂ has four fluorine atoms and no hydrogen.",
        "The monomer tetrafluoroethene, CF₂=CF₂, opens its double bond: the repeat unit is two carbons joined by a single bond, each carrying two F atoms, with bonds out to each side.",
        "Each carbon can form only four bonds. Tetrafluoroethene has NO hydrogen — the four F atoms replace all four H atoms of ethene.",
      ],
      explanation:
        "Tetrafluoroethene is ethene with all four H atoms replaced by F: CF₂=CF₂. In addition polymerisation the C=C double bond opens up and the monomers join into a long chain: n CF₂=CF₂ → –[CF₂–CF₂]ₙ–. The repeat unit is two carbons joined by a single bond, each with two F atoms. PTFE, like all addition polymers, is very unreactive and does not biodegrade.",
      hints: ["'Tetrafluoro' means four fluorine atoms on ethene.", "What happens to the C=C double bond in addition polymerisation?"],
      strategy: "Think about electrons",
    },
    {
      id: "or-m27",
      topic: "organic",
      section: "organic-crude",
      difficulty: "core",
      question: "Compare the fuel oil fraction with the gasoline fraction from crude oil. Which row is correct for fuel oil?",
      table: {
        headers: ["Option", "Boiling point", "Viscosity", "Colour"],
        rows: [
          ["A", "higher", "higher", "darker"],
          ["B", "higher", "lower", "darker"],
          ["C", "lower", "higher", "paler"],
          ["D", "lower", "lower", "paler"],
        ],
      },
      options: ["A", "B", "C", "D"],
      answerIndex: 0,
      optionFeedback: [
        "Fuel oil has longer molecules: stronger intermolecular forces give a higher boiling point and higher viscosity, and it is darker in colour.",
        "Boiling point and colour are right, but longer molecules flow LESS easily, so viscosity is higher, not lower.",
        "Fuel oil collects near the bottom of the column, where it is hottest — it has a HIGHER boiling point than gasoline.",
        "This describes gasoline compared with fuel oil — the reverse of what is asked.",
      ],
      explanation:
        "Going down the fractionating column the molecules get longer (gasoline ~C₅–C₁₀, fuel oil ~C₂₀–C₄₀). Longer molecules have stronger intermolecular forces, so boiling point increases, viscosity increases (thicker, flows less easily) and colour gets darker. They are also harder to ignite. So fuel oil: higher, higher, darker.",
      hints: ["Which fraction has the longer hydrocarbon molecules?", "Longer molecules → stronger forces between molecules → what happens to each property?"],
      strategy: "Read the data carefully",
    },
  ],
};
