import type { MCQ, QuestionSet } from "../../types";

const questions: MCQ[] = [
  {
    id: "bd-m01",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "warmup",
    question: "Magnesium is in group 2 of the Periodic Table. Which of these describes how a magnesium atom forms an ion?",
    options: [
      "It gains two electrons to form Mg²⁻",
      "It loses two electrons to form Mg²⁺",
      "It loses two electrons to form Mg²⁻",
      "It shares two electrons to form Mg²⁺",
    ],
    answerIndex: 1,
    optionFeedback: [
      "Gaining electrons is what non-metals do. A group 2 metal has 2 outer electrons, and losing 2 is far easier than gaining 6.",
      "A magnesium atom (2,8,2) loses its two outer electrons, leaving 12 protons and 10 electrons: an overall charge of 2+.",
      "You have the right process but the wrong sign. Electrons are negative, so losing two leaves the ion with a 2+ charge, not 2−.",
      "Sharing electrons makes a covalent bond, which does not produce ions. Metals transfer (lose) electrons when they react with non-metals.",
    ],
    explanation:
      "Metals lose their outer-shell electrons to form positive ions with a full outer shell. Magnesium (2,8,2) loses 2 electrons → Mg²⁺ (2,8). The charge is (number of protons) − (number of electrons) = 12 − 10 = +2.",
    hints: ["Metals form positive ions. How many electrons are in magnesium's outer shell?"],
    strategy: "Think about electrons",
  },
  {
    id: "bd-m02",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "warmup",
    question: "What is the formula of ammonium sulfate?",
    options: ["NH₄SO₄", "NH₄(SO₄)₂", "(NH₄)₂SO₄", "(NH₄)₃SO₄"],
    answerIndex: 2,
    optionFeedback: [
      "This treats both ions as having the same size of charge. Sulfate is SO₄²⁻, so one NH₄⁺ only cancels half of its charge.",
      "This puts the brackets on the wrong ion. It gives +1 and −4 overall, which does not balance.",
      "Two NH₄⁺ ions (+2) balance one SO₄²⁻ ion (−2), and the brackets show there are two whole ammonium ions.",
      "Three ammonium ions give +3, but sulfate is only 2−, so the charges do not cancel. You may have confused sulfate with phosphate.",
    ],
    explanation:
      "Ammonium is NH₄⁺ and sulfate is SO₄²⁻. To cancel the 2− you need two NH₄⁺. When more than one compound ion is needed, put it in brackets with the number outside: (NH₄)₂SO₄.",
    hints: ["Write the charges first: ammonium is 1+; what is the charge on sulfate?"],
    strategy: "Balance the equation",
  },
  {
    id: "bd-m03",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "warmup",
    question: "Which statement best describes a covalent bond?",
    options: [
      "A shared pair of electrons between two atoms",
      "Electrons transferred from a metal to a non-metal",
      "Attraction between positive ions and free electrons",
      "Weak attraction between two separate molecules",
    ],
    answerIndex: 0,
    optionFeedback: [
      "A covalent bond is a shared pair of electrons, held by the attraction of both nuclei for that pair.",
      "This is how ionic bonding forms. Covalent bonding is between non-metal atoms, which share electrons rather than transferring them.",
      "This describes metallic bonding: positive metal ions attracted to delocalised electrons.",
      "This describes intermolecular forces, which are much weaker than the covalent bonds inside a molecule.",
    ],
    explanation:
      "Covalent bonds form between non-metal atoms that share pairs of electrons so that each atom gets a full outer shell. The bond is the strong electrostatic attraction between the shared pair and the two nuclei. Learn to tell the three bonding types apart, and keep them separate from intermolecular forces.",
    hints: ["Which type of bonding happens between two non-metal atoms, such as in H₂?"],
    strategy: "Recall the definition",
  },
  {
    id: "bd-m04",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "warmup",
    question: "How many pairs of electrons are shared between the two atoms in a nitrogen molecule, N₂?",
    options: ["1", "2", "5", "3"],
    answerIndex: 3,
    optionFeedback: [
      "One shared pair would give each nitrogen only 6 outer electrons. Nitrogen needs 3 more electrons, not 1.",
      "Two shared pairs is a double bond, as in O₂. Oxygen (group 6) needs 2 electrons, but nitrogen (group 5) needs 3.",
      "5 is the number of outer electrons in each nitrogen atom, not the number of shared pairs.",
      "Each N (2,5) needs 3 more electrons, so the atoms share 3 pairs: a triple bond, N≡N.",
    ],
    explanation:
      "Nitrogen is in group 5 with 5 outer electrons. To reach 8 it must share 3 of them, so N₂ has a triple bond (3 shared pairs = 6 shared electrons). Each N also keeps one lone pair: 6 shared + 2 non-bonding = 8 outer electrons.",
    hints: ["Nitrogen is in group 5. How many more electrons does each atom need to reach 8?"],
    strategy: "Think about electrons",
  },
  {
    id: "bd-m05",
    topic: "bonding",
    section: "bonding-metallic",
    difficulty: "warmup",
    question: "Which statement describes metallic bonding?",
    options: [
      "Attraction between positive ions and negative ions",
      "A shared pair of electrons between metal atoms",
      "Attraction between positive ions and delocalised electrons",
      "Weak forces between layers of metal atoms",
    ],
    answerIndex: 2,
    optionFeedback: [
      "This describes ionic bonding. A pure metal contains no negative ions, only positive ions and electrons.",
      "Metal atoms do not form localised shared pairs. Their outer electrons are delocalised over the whole structure.",
      "Metallic bonding is the strong electrostatic attraction between the positive metal ions and the sea of delocalised electrons.",
      "The forces in a metal are strong, which is why most metals have high melting points. Weak forces between layers describes graphite.",
    ],
    explanation:
      "In a metal, atoms release their outer electrons into a 'sea' of delocalised electrons, leaving positive ions arranged in layers. Metallic bonding is the strong electrostatic attraction between these positive ions and the delocalised electrons. Learn this sentence exactly: it earns a mark in almost every metals question.",
    hints: ["Picture the copper lattice diagram: what two kinds of particle does it show?"],
    strategy: "Recall the definition",
  },
  {
    id: "bd-m06",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "core",
    question: "Aluminium is in group 3 and oxygen is in group 6. What is the formula of aluminium oxide?",
    options: ["Al₂O₃", "AlO", "Al₃O₂", "Al₂O"],
    answerIndex: 0,
    optionFeedback: [
      "Al³⁺ and O²⁻: two Al³⁺ give +6 and three O²⁻ give −6, so the charges cancel.",
      "This assumes both ions have the same size of charge. Al³⁺ and O²⁻ do not cancel one-to-one.",
      "This swaps the numbers the wrong way round: 3 × Al³⁺ = +9 and 2 × O²⁻ = −4, which does not balance.",
      "Two Al³⁺ make +6 but one O²⁻ is only −2. You need three oxide ions.",
    ],
    explanation:
      "Group 3 → Al³⁺; group 6 → O²⁻. The lowest common multiple of 3 and 2 is 6, so you need 2 Al³⁺ (+6) and 3 O²⁻ (−6): Al₂O₃. The quick 'swap and drop' method (the charge of one ion becomes the number of the other) works, but always check the charges cancel.",
    hints: [
      "Work out the charge on each ion from its group number.",
      "Find the smallest total charge that both 3 and 2 divide into.",
    ],
    strategy: "Balance the equation",
  },
  {
    id: "bd-m07",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "core",
    question: "Why does sodium chloride have a high melting point?",
    options: [
      "Its strong covalent bonds need a lot of energy to break",
      "Its molecules have strong intermolecular forces",
      "Its delocalised electrons attract the ions strongly",
      "Strong electrostatic forces act between oppositely charged ions",
    ],
    answerIndex: 3,
    optionFeedback: [
      "Sodium chloride is ionic, formed from a metal and a non-metal. There are no covalent bonds between Na⁺ and Cl⁻.",
      "Sodium chloride has no molecules; it is a giant ionic lattice. Using 'intermolecular forces' for an ionic compound loses the mark.",
      "Delocalised electrons belong to metals and graphite. In NaCl every electron is held by an ion.",
      "A giant lattice of Na⁺ and Cl⁻ ions held by many strong electrostatic attractions in all directions needs a lot of energy to break up.",
    ],
    explanation:
      "Sodium chloride is a giant ionic lattice. Each ion is surrounded by ions of opposite charge, and the strong electrostatic attractions act in all directions. Melting means overcoming a huge number of these attractions, which needs a lot of energy, so the melting point is high (801 °C).",
    hints: [
      "Is sodium chloride ionic, simple molecular or metallic?",
      "What kind of attraction holds Na⁺ and Cl⁻ together?",
    ],
    strategy: "Think about particles",
  },
  {
    id: "bd-m08",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "core",
    question: "The table shows some properties of four substances. Which substance is most likely to have a giant ionic structure?",
    table: {
      headers: ["Substance", "Melting point (°C)", "Conducts when solid?", "Conducts when molten?"],
      rows: [
        ["A", "1083", "yes", "yes"],
        ["B", "770", "no", "yes"],
        ["C", "−114", "no", "no"],
        ["D", "3550", "no", "no"],
      ],
    },
    options: ["A", "B", "C", "D"],
    answerIndex: 1,
    optionFeedback: [
      "Conducting as a solid shows mobile electrons: A is a metal (these are copper's values).",
      "A high melting point, no conduction as a solid, but conduction when molten is the signature of an ionic compound: the ions become free to move.",
      "A melting point of −114 °C means only weak intermolecular forces: C is a simple molecular substance.",
      "Very high melting point with no conduction in any state points to a giant covalent structure such as diamond.",
    ],
    explanation:
      "Use conductivity to sort structures. Metals conduct as solids and liquids. Ionic compounds conduct only when molten or dissolved, because the ions must be free to move. Giant covalent and simple molecular substances do not conduct (graphite is the exception), and their melting points tell them apart: very high or low.",
    hints: [
      "Which type of structure conducts when molten but not when solid?",
      "Rule out the substance that conducts as a solid first.",
    ],
    strategy: "Read the data carefully",
  },
  {
    id: "bd-m09",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "core",
    question: "Solid potassium bromide does not conduct electricity, but potassium bromide solution does. Why?",
    options: [
      "In solution, electrons are free to move through the liquid",
      "In solution, the covalent bonds break and release electrons",
      "In solution, the ions are free to move and carry charge",
      "In the solid, there are no ions present at all",
    ],
    answerIndex: 2,
    optionFeedback: [
      "This is the classic error. Electrons do not move through an ionic compound or its solution; the charge is carried by moving ions.",
      "Potassium bromide is ionic, not covalent, and dissolving does not release free electrons.",
      "When the compound dissolves, the K⁺ and Br⁻ ions separate and can move, so they carry charge through the solution.",
      "The solid is made of ions; they just cannot move because they are held in fixed positions in the lattice.",
    ],
    explanation:
      "To conduct, a substance needs charged particles that can move. Solid KBr contains ions, but they are held in fixed positions in the lattice. When it melts or dissolves, the lattice breaks up and the ions are free to move and carry charge. In examiner terms: say 'ions', never 'electrons', for an ionic compound.",
    hints: [
      "Are there charged particles in the solid? Can they move?",
      "Which particles carry charge in an ionic compound: ions or electrons?",
    ],
    strategy: "Think about particles",
  },
  {
    id: "bd-m10",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "Methane, CH₄, boils at −162 °C. Why is the boiling point of methane so low?",
    options: [
      "Weak intermolecular forces need little energy to overcome",
      "The C–H covalent bonds are weak and break easily",
      "Methane contains ions that are only weakly attracted",
      "Methane has a giant structure with few bonds",
    ],
    answerIndex: 0,
    optionFeedback: [
      "Boiling separates whole CH₄ molecules from each other, which only means overcoming the weak forces between molecules.",
      "C–H bonds are strong covalent bonds and they do not break when methane boils; the molecules stay intact as CH₄ in the gas.",
      "Methane is a covalent compound of two non-metals: it has no ions.",
      "Methane is a simple molecular substance made of separate small molecules, not a giant structure.",
    ],
    explanation:
      "Methane is simple molecular. Inside each molecule the C–H covalent bonds are strong, but between molecules there are only weak intermolecular forces. Boiling overcomes only these weak forces, so little energy is needed and the boiling point is low.",
    hints: [
      "When methane boils, are CH₄ molecules broken apart, or just separated from each other?",
      "Which forces act between separate molecules?",
    ],
    strategy: "Think about particles",
  },
  {
    id: "bd-m11",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "In a dot-and-cross diagram of ethene, C₂H₄, how many electrons are shared between the two carbon atoms?",
    options: ["2", "4", "6", "8"],
    answerIndex: 1,
    optionFeedback: [
      "2 shared electrons is a single bond. Each carbon would then have only 7 outer electrons with its two C–H bonds.",
      "Ethene has a C=C double bond: 2 shared pairs, which is 4 electrons.",
      "6 shared electrons would be a triple bond, as in N₂. Each carbon would then have 10 outer electrons.",
      "8 is the number of outer electrons around each carbon, not the number shared between the two carbons.",
    ],
    explanation:
      "Each carbon has 4 outer electrons. In ethene each C forms two C–H single bonds (2 pairs) and shares 2 pairs with the other carbon (a double bond). Count for one carbon: 2 + 2 (C–H bonds) + 4 (C=C) = 8 outer electrons. Shared between the carbons: 2 pairs = 4 electrons.",
    hints: [
      "How many bonds must each carbon make? Two of them go to hydrogen atoms.",
      "Remember that each shared pair contains 2 electrons.",
    ],
    strategy: "Think about electrons",
  },
  {
    id: "bd-m12",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "Why does graphite conduct electricity?",
    options: [
      "Its ions are free to move between the layers",
      "Its layers can slide over each other easily",
      "Each carbon atom forms four strong covalent bonds",
      "Each carbon has one delocalised electron that can move",
    ],
    answerIndex: 3,
    optionFeedback: [
      "Graphite is pure carbon joined by covalent bonds; it contains no ions.",
      "Sliding layers explain why graphite is soft and a lubricant, not why it conducts.",
      "Four bonds per carbon describes diamond, where every outer electron is used in bonding, so diamond does not conduct.",
      "Each carbon bonds to only three others, so its fourth outer electron is delocalised and free to move along the layers, carrying charge.",
    ],
    explanation:
      "In graphite each carbon atom is covalently bonded to three others in flat hexagonal layers. The fourth outer electron from each atom is delocalised: it can move along the layers and carry charge. Keep the two graphite explanations separate: delocalised electrons explain conduction; weak forces between layers explain the slipperiness.",
    hints: [
      "To conduct, a substance needs charged particles that can move. Which particles could they be in graphite?",
      "How many of carbon's four outer electrons are used in bonding in graphite?",
    ],
    strategy: "Compare and contrast",
  },
  {
    id: "bd-m13",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "The table shows the boiling points of four alkanes. Which statement correctly explains the trend?",
    table: {
      headers: ["Alkane", "Mr", "Boiling point (°C)"],
      rows: [
        ["methane, CH₄", "16", "−162"],
        ["ethane, C₂H₆", "30", "−89"],
        ["propane, C₃H₈", "44", "−42"],
        ["butane, C₄H₁₀", "58", "−1"],
      ],
    },
    options: [
      "Larger molecules have more covalent bonds to break",
      "The C–H bonds get stronger as the molecules get larger",
      "Larger molecules have stronger intermolecular forces",
      "Heavier molecules move faster, so they need more energy",
    ],
    answerIndex: 2,
    optionFeedback: [
      "Tempting, because larger molecules do contain more bonds, but boiling does not break covalent bonds at all.",
      "C–H bond strength stays about the same, and covalent bonds are not broken on boiling anyway.",
      "As Mr increases, the intermolecular forces between molecules get stronger, so more energy is needed to overcome them and the boiling point rises.",
      "Heavier molecules actually move more slowly at the same temperature, and particle speed is not the reason for the trend.",
    ],
    explanation:
      "All four are simple molecular substances. Boiling only overcomes the intermolecular forces between molecules. These forces increase as the size of the molecules (Mr) increases, so more energy is needed and the boiling point rises. The same idea explains why the halogens go from gases to a liquid to a solid down group 7.",
    hints: [
      "When butane boils, what is actually overcome?",
      "How do the forces between molecules change as the molecules get bigger?",
    ],
    strategy: "Read the data carefully",
  },
  {
    id: "bd-m14",
    topic: "bonding",
    section: "bonding-metallic",
    difficulty: "core",
    question: "Copper can be drawn out into thin wires. Which explanation is correct?",
    options: [
      "Layers of positive ions can slide over each other",
      "The delocalised electrons slide over each other",
      "The metallic bonds break and then quickly re-form",
      "The copper atoms are held by weak forces in layers",
    ],
    answerIndex: 0,
    optionFeedback: [
      "The layers of Cu²⁺ ions slide past each other while staying surrounded by delocalised electrons, so the metallic bonding is maintained and the wire does not break.",
      "It is the layers of ions that slide; the electrons are a mobile 'sea' around them, not layers.",
      "The point is that the bonding is NOT broken: the delocalised electrons move with the ions, so the attraction is kept as the layers move.",
      "Metallic bonding is strong (copper melts at 1085 °C). Weak forces between layers is the graphite explanation.",
    ],
    explanation:
      "Copper is ductile (drawn into wires) and malleable (hammered into shape) because its positive ions are arranged in layers that can slide over each other. As they slide, the delocalised electrons move with them, so the electrostatic attraction (the metallic bonding) is kept throughout and the metal does not shatter, unlike an ionic crystal.",
    hints: [
      "What particles are arranged in layers in a metal?",
      "Does the metallic bonding break when the metal changes shape?",
    ],
    strategy: "Think about particles",
  },
  {
    id: "bd-m15",
    topic: "bonding",
    section: "bonding-metallic",
    difficulty: "core",
    question: "(Stretch) Brass, an alloy of copper and zinc, is harder than pure copper. Why?",
    options: [
      "Zinc forms ionic bonds with copper in the alloy",
      "The alloy has more delocalised electrons per atom",
      "Zinc atoms fill gaps, so the layers pack more tightly",
      "Different-sized atoms disrupt the layers so they slide less easily",
    ],
    answerIndex: 3,
    optionFeedback: [
      "Both copper and zinc are metals, so there is no ionic bonding between them; the alloy still has metallic bonding.",
      "The number of delocalised electrons affects melting point and conductivity, but it is not the reason alloys are harder.",
      "Tempting, but the key idea is disruption: the zinc atoms are a different size and distort the regular layers.",
      "The zinc atoms are a different size from copper atoms, so they disrupt the regular arrangement and the layers cannot slide over each other as easily.",
    ],
    explanation:
      "In a pure metal all atoms are the same size, so the layers are regular and slide easily. In an alloy, atoms of a different size distort the layers; the layers can no longer slide over each other as easily, so the alloy is harder and stronger. The same idea explains why steel is harder than pure iron.",
    hints: [
      "Why is a pure metal soft? Think about its layers.",
      "What happens to the regular layers when atoms of a different size are mixed in?",
    ],
    strategy: "Think about particles",
  },
  {
    id: "bd-m16",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "challenge",
    question: "Element X is in group 2 and element Y is in group 5. X and Y react to form an ionic compound. What is its formula?",
    options: ["X₂Y₃", "X₃Y₂", "XY", "X₂Y₅"],
    answerIndex: 1,
    optionFeedback: [
      "This swaps the numbers the wrong way: 2 × X²⁺ = +4 but 3 × Y³⁻ = −9.",
      "X loses 2 electrons → X²⁺; Y gains 3 → Y³⁻. Three X²⁺ (+6) balance two Y³⁻ (−6).",
      "This assumes the ion charges are equal. X²⁺ and Y³⁻ do not cancel one-to-one.",
      "This uses the group numbers directly instead of the ion charges. A group 5 non-metal gains 3 electrons; it does not form a 5− or 5+ ion.",
    ],
    explanation:
      "Group 2 metals lose 2 electrons → X²⁺. Group 5 non-metals gain 3 electrons (8 − 5) → Y³⁻. The lowest common multiple of 2 and 3 is 6: 3 X²⁺ = +6 and 2 Y³⁻ = −6, so the formula is X₃Y₂. A real example is magnesium nitride, Mg₃N₂.",
    hints: [
      "A group 5 element gains electrons. How many does it need to reach 8?",
      "Write the two ion charges, then find a total charge both divide into.",
      "Think of magnesium reacting with nitrogen.",
    ],
    strategy: "Apply it to a new situation",
  },
  {
    id: "bd-m17",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "challenge",
    question: "Buckminsterfullerene, C₆₀, turns into a gas at about 600 °C, whereas diamond does not melt until above 3500 °C. Which explanation is correct?",
    options: [
      "The covalent bonds in C₆₀ are weaker than in diamond",
      "C₆₀ has delocalised electrons, but diamond has none",
      "Only weak intermolecular forces act between C₆₀ molecules",
      "C₆₀ is ionic, so its lattice breaks up more easily",
    ],
    answerIndex: 2,
    optionFeedback: [
      "Covalent bonds are not broken when C₆₀ turns to gas: the C₆₀ molecules stay intact.",
      "Delocalised electrons relate to conductivity, not to the energy needed to change state here.",
      "C₆₀ is simple molecular: changing state overcomes only the weak forces between molecules, whereas diamond requires breaking many strong covalent bonds.",
      "C₆₀ is pure carbon, a non-metal, so it cannot be ionic.",
    ],
    explanation:
      "Diamond is giant covalent: every atom is joined by strong covalent bonds, and melting means breaking very many of them. C₆₀ is a simple molecular form of carbon: each molecule is a closed cage of 60 atoms, and between molecules there are only weak intermolecular forces. These need far less energy to overcome, which is also why C₆₀ is soft.",
    hints: [
      "Is C₆₀ a giant structure or made of separate molecules?",
      "When C₆₀ changes state, is anything inside the molecules broken?",
      "Compare what must be overcome in each case.",
    ],
    strategy: "Compare and contrast",
  },
  {
    id: "bd-m18",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "challenge",
    question: "In a dot-and-cross diagram of carbon dioxide, CO₂, how many non-bonding (lone pair) electrons are there in the whole molecule?",
    options: ["4", "12", "16", "8"],
    answerIndex: 3,
    optionFeedback: [
      "4 is the number of lone-pair electrons on ONE oxygen atom. There are two oxygen atoms.",
      "12 is the number of outer electrons of the two oxygen atoms (2 × 6) before bonding; some of these are used in the double bonds.",
      "16 is the total number of outer electrons in the molecule (4 + 6 + 6), including the 8 shared in the two double bonds.",
      "Each oxygen has 2 lone pairs (4 electrons), carbon has none, so the molecule has 2 × 4 = 8 non-bonding electrons.",
    ],
    explanation:
      "Total outer electrons: C 4 + O 6 + O 6 = 16. Two C=O double bonds use 2 × 4 = 8 shared electrons. The rest, 16 − 8 = 8, are non-bonding: two lone pairs on each oxygen. Carbon uses all four of its outer electrons in bonding, so it has no lone pairs.",
    hints: [
      "Start with the total number of outer electrons from one C and two O atoms.",
      "Each C=O double bond contains how many electrons?",
      "Subtract the shared electrons from the total.",
    ],
    strategy: "Think about electrons",
  },
  {
    id: "bd-m19",
    topic: "bonding",
    section: "bonding-metallic",
    difficulty: "challenge",
    question: "Sodium melts at 98 °C but magnesium melts at 650 °C. Which statement best explains this?",
    options: [
      "Mg²⁺ ions have a higher charge and there are more delocalised electrons, so the attraction is stronger",
      "Magnesium atoms have more electron shells than sodium atoms, so they are held more strongly",
      "Magnesium has stronger intermolecular forces between its atoms than sodium",
      "Sodium ions are smaller than magnesium ions, so they slide past each other more easily",
    ],
    answerIndex: 0,
    optionFeedback: [
      "Each Mg atom gives 2 electrons to the sea (Na gives 1) and forms a 2+ ion, so the electrostatic attraction between ions and delocalised electrons is stronger and needs more energy to overcome.",
      "Both are in period 3, so both atoms have three occupied shells. The number of shells is not the difference.",
      "Metals have metallic bonding, not intermolecular forces: there are no molecules in a metal.",
      "Mg²⁺ is actually smaller than Na⁺, and sliding layers explain malleability, not melting point.",
    ],
    explanation:
      "Melting a metal means overcoming the electrostatic attraction between the positive ions and the delocalised electrons. Sodium forms Na⁺ and contributes one delocalised electron per atom; magnesium forms Mg²⁺ and contributes two. Higher ion charge plus more delocalised electrons gives stronger metallic bonding, so more energy is needed and the melting point is higher.",
    hints: [
      "What charge does each metal ion have?",
      "How many electrons does each atom release into the 'sea'?",
      "How does that affect the strength of the electrostatic attraction?",
    ],
    strategy: "Apply it to a new situation",
  },
  {
    id: "bd-m20",
    topic: "bonding",
    section: "bonding-metallic",
    difficulty: "challenge",
    question: "Solid sodium and solid sodium chloride both contain Na⁺ ions. Why does solid sodium conduct electricity while solid sodium chloride does not?",
    options: [
      "In sodium metal, the Na⁺ ions are free to move through the solid",
      "Sodium has delocalised electrons; in NaCl the ions are fixed in place",
      "Electrons in sodium chloride are held in covalent bonds",
      "Sodium has weaker bonding, so its particles can move around",
    ],
    answerIndex: 1,
    optionFeedback: [
      "The ions in solid sodium are in fixed positions in the lattice too. It is the delocalised electrons that move.",
      "Sodium metal has delocalised electrons that move and carry charge. NaCl has no delocalised electrons, and its ions are fixed in the solid lattice.",
      "Sodium chloride is ionic, not covalent. The point is that it has no mobile charged particles in the solid.",
      "Weaker bonding does not make particles mobile in a solid. Conduction depends on charged particles being free to move.",
    ],
    explanation:
      "Conduction needs mobile charged particles. In a metal they are the delocalised electrons, which move through the lattice even in the solid. In an ionic solid the only charged particles are the ions, and they are locked in the lattice, so the solid cannot conduct until it is melted or dissolved. Different structure, different charge carrier.",
    hints: [
      "Which particles carry the current in a metal?",
      "Are the ions in solid sodium chloride able to move?",
      "Compare the charge carriers in the two structures.",
    ],
    strategy: "Compare and contrast",
  },
  {
    id: "bd-m21",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "warmup",
    question: "Diamond, graphite and C₆₀ fullerene are all allotropes of carbon. What are allotropes?",
    options: [
      "Atoms of the same element with different numbers of neutrons",
      "Different structural forms of the same element",
      "Compounds with the same molecular formula but different structures",
      "Elements in the same group with similar properties",
    ],
    answerIndex: 1,
    optionFeedback: [
      "That describes isotopes (e.g. carbon-12 and carbon-14) — a difference inside the nucleus, not in how the atoms are bonded together.",
      "Allotropes are the same element with its atoms bonded together in different arrangements — diamond, graphite and C₆₀ are all pure carbon.",
      "That describes structural isomers, which are compounds (e.g. butane and methylpropane), not forms of one element.",
      "That describes a group (family) of the Periodic Table — different elements, not forms of one element.",
    ],
    explanation:
      "Allotropes are different structural forms of the same element in the same physical state. Diamond (each C bonded to 4 others, giant covalent), graphite (layers, each C bonded to 3) and C₆₀ (simple molecules) are all made only of carbon atoms, but their different bonding gives them very different hardness, melting points and conductivity.",
    hints: ["All three substances contain only carbon atoms — so what is different about them?"],
    strategy: "Recall the definition",
  },
  {
    id: "bd-m22",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "A molecule is defined as two or more atoms covalently bonded together. Which of these substances is made of molecules?",
    options: ["Argon, Ar", "Sodium chloride, NaCl", "Nitrogen, N₂", "Copper, Cu"],
    answerIndex: 2,
    optionFeedback: [
      "Argon has a full outer shell, so its atoms exist singly (monatomic) — a single atom is not a molecule.",
      "Sodium chloride is a giant ionic lattice of Na⁺ and Cl⁻ ions held by ionic bonds, not separate molecules.",
      "Each N₂ particle is two nitrogen atoms joined by a covalent (triple) bond — a molecule of an element.",
      "Copper is a giant metallic lattice of positive ions in a sea of delocalised electrons — no covalent molecules.",
    ],
    explanation:
      "A molecule is two or more atoms covalently bonded together. The atoms can be the same (N₂, O₂, Cl₂ — molecules of elements) or different (H₂O, CO₂ — molecules of compounds). Noble gases are single atoms; ionic compounds and metals are giant lattices, so the word 'molecule' should never be used for them.",
    hints: ["Which substance contains covalent bonds?", "Look for a substance made of small, separate groups of atoms."],
    strategy: "Recall the definition",
  },
  {
    id: "bd-m23",
    topic: "bonding",
    section: "bonding-covalent",
    difficulty: "core",
    question: "In a dot-and-cross diagram of ethane, C₂H₆, how many pairs of electrons are shared in the whole molecule?",
    options: ["6", "8", "14", "7"],
    answerIndex: 3,
    optionFeedback: [
      "Six is the number of C–H bonds — you have left out the C–C bond joining the two carbon atoms.",
      "Eight would include an extra pair — ethane has a C–C SINGLE bond (one pair), not a double bond like ethene.",
      "Fourteen is the number of shared ELECTRONS (7 pairs × 2), not the number of pairs.",
      "6 C–H bonds + 1 C–C bond = 7 single covalent bonds, each a shared pair.",
    ],
    explanation:
      "Each carbon forms 4 bonds and each hydrogen 1. In ethane each carbon bonds to 3 hydrogens and to the other carbon: 6 C–H + 1 C–C = 7 single bonds = 7 shared pairs (14 electrons). There are no lone pairs. Compare ethene, C₂H₄: 4 C–H + a C=C double bond = 6 shared pairs.",
    hints: ["Draw the displayed formula first: how many C–H bonds are there?", "Don't forget the bond that joins the two carbons, and count PAIRS not electrons."],
    strategy: "Think about electrons",
  },
  {
    id: "bd-m24",
    topic: "bonding",
    section: "bonding-ionic",
    difficulty: "core",
    question: "Which row correctly identifies the type of bonding in each substance from its formula?",
    table: {
      headers: ["Option", "MgCl₂", "SO₂", "Zn"],
      rows: [
        ["A", "covalent", "ionic", "metallic"],
        ["B", "ionic", "covalent", "metallic"],
        ["C", "ionic", "ionic", "covalent"],
        ["D", "metallic", "covalent", "ionic"],
      ],
    },
    options: ["A", "B", "C", "D"],
    answerIndex: 1,
    optionFeedback: [
      "MgCl₂ is a metal + non-metal (ionic), and SO₂ is two non-metals (covalent) — this row swaps them.",
      "Metal + non-metal → ionic (MgCl₂); non-metals only → covalent (SO₂); a metal element on its own → metallic (Zn).",
      "SO₂ contains no metal, so electrons are shared, not transferred; and zinc is a metal, so it has metallic bonding.",
      "Magnesium chloride is a compound of a metal and a non-metal, so it is ionic — metallic bonding is only in metals and alloys.",
    ],
    explanation:
      "Use the Periodic Table to classify each element as a metal or a non-metal. Metal + non-metal → electrons transferred → ionic bonding. Non-metal + non-metal → electrons shared → covalent bonding. A metal element (or alloy) → positive ions in a sea of delocalised electrons → metallic bonding.",
    hints: ["Is each element a metal or a non-metal?", "Which combination transfers electrons, and which shares them?"],
    strategy: "Eliminate wrong options",
  },
];

export const mcq: QuestionSet<MCQ> = {
  id: "mcq-bonding",
  title: "Multiple choice · Bonding & Structure",
  subtitle: "Ionic, covalent and metallic bonding: formulae, dot-and-cross and explaining properties",
  topic: "bonding",
  questions,
};
