import type { MCQ, QuestionSet } from "../../types";

export const mcq: QuestionSet<MCQ> = {
  id: "mcq-acids",
  title: "Multiple choice · Acids, Salts & Chemical Tests",
  subtitle: "Indicators, pH, titration technique, salt preparations and identifying ions — the heaviest topic on your teacher's paper.",
  topic: "acids",
  questions: [
    // ---------------- WARM-UP ----------------
    {
      id: "ac-m01",
      topic: "acids",
      section: "acids-acids",
      difficulty: "warmup",
      question: "A few drops of methyl orange are added to sodium hydroxide solution. What colour is the solution?",
      options: ["red", "yellow", "orange", "pink"],
      answerIndex: 1,
      optionFeedback: [
        "Methyl orange is red in ACID. Sodium hydroxide is an alkali, so it cannot be red.",
        "Methyl orange is yellow in alkalis such as sodium hydroxide.",
        "Orange is the colour at the end point, when acid and alkali have exactly neutralised — not in pure alkali.",
        "Pink is phenolphthalein's colour in alkali. Don't mix up the two titration indicators.",
      ],
      explanation:
        "Methyl orange is red in acid and yellow in alkali; at the end point of a titration it is orange. Phenolphthalein is colourless in acid and pink in alkali. In the teacher's Q5 the acid is added to sodium hydroxide, so the colour change is yellow → orange.",
      hints: ["Methyl orange has three colours to learn: one for acid, one for alkali and one for the end point in between."],
      strategy: "Recall the definition",
    },
    {
      id: "ac-m02",
      topic: "acids",
      section: "acids-acids",
      difficulty: "warmup",
      question: "Which ion is present in all aqueous solutions of acids?",
      options: ["OH⁻(aq)", "Cl⁻(aq)", "H⁺(aq)", "H₂O(l)"],
      answerIndex: 2,
      optionFeedback: [
        "Hydroxide ions are what ALKALIS release in water, not acids.",
        "Chloride ions are only in hydrochloric acid — sulfuric and nitric acids contain no chloride.",
        "Acids release hydrogen ions, H⁺(aq), when they dissolve in water.",
        "Water is a molecule, not an ion, and it is present in every aqueous solution, acidic or not.",
      ],
      explanation:
        "An acid is a source of hydrogen ions, H⁺(aq), in water; an alkali is a source of hydroxide ions, OH⁻(aq). The negative ion (Cl⁻, SO₄²⁻, NO₃⁻) varies with the acid and decides the name of the salt formed.",
      hints: ["Think about what HCl, H₂SO₄ and HNO₃ all have in their formulae."],
      strategy: "Recall the definition",
    },
    {
      id: "ac-m03",
      topic: "acids",
      section: "acids-titration",
      difficulty: "warmup",
      question: "Which piece of apparatus should be used to measure exactly 25.0 cm³ of potassium hydroxide solution into a conical flask for a titration?",
      options: ["volumetric pipette", "measuring cylinder", "beaker", "gas syringe"],
      answerIndex: 0,
      optionFeedback: [
        "A volumetric pipette (used with a pipette filler) delivers exactly 25.0 cm³.",
        "A measuring cylinder is far less precise — it cannot measure to ±0.05 cm³ reliably, so it is not used for titrations.",
        "Beakers have only rough markings; they are never used to measure volumes accurately.",
        "A gas syringe measures volumes of gas produced in a reaction, not liquids for a titration.",
      ],
      explanation:
        "In a titration the alkali is measured with a (volumetric) pipette and pipette filler, and the acid is added from a burette. Both are precise to about ±0.05 cm³ or better; a measuring cylinder is not precise enough. This was Q5(a)(i) on your teacher's paper.",
      hints: ["You need a piece of glassware calibrated to deliver ONE fixed volume very precisely."],
      strategy: "Recall the definition",
    },
    {
      id: "ac-m04",
      topic: "acids",
      section: "acids-salts",
      difficulty: "warmup",
      question: "Which of these salts is insoluble in water?",
      options: ["sodium carbonate", "zinc nitrate", "ammonium chloride", "barium sulfate"],
      answerIndex: 3,
      optionFeedback: [
        "Most carbonates are insoluble, but sodium, potassium and ammonium carbonates are the exceptions — they dissolve.",
        "All nitrates are soluble, without exception.",
        "All ammonium salts are soluble, and most chlorides are too.",
        "Barium sulfate is one of the insoluble sulfates (with calcium and lead(II) sulfate).",
      ],
      explanation:
        "Solubility rules: all sodium, potassium and ammonium salts and all nitrates are soluble. Common sulfates are soluble except barium, calcium and lead(II) sulfate. Barium sulfate is therefore made by precipitation, and its white precipitate is the positive result in the sulfate test.",
      hints: ["Check each against the rules: Na/K/NH₄ salts always soluble; nitrates always soluble; which sulfates are the exceptions?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ac-m05",
      topic: "acids",
      section: "acids-tests",
      difficulty: "warmup",
      question: "Which row correctly matches a gas with its test result?",
      options: [
        "hydrogen — relights a glowing splint",
        "oxygen — squeaky pop with a lighted splint",
        "chlorine — bleaches damp litmus paper",
        "ammonia — turns damp blue litmus red",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Relighting a glowing splint is the test for OXYGEN. Hydrogen gives a squeaky pop with a lighted splint.",
        "The squeaky pop is the HYDROGEN test; oxygen relights a glowing splint. The two results have been swapped.",
        "Chlorine bleaches damp litmus paper (it turns white).",
        "Ammonia is alkaline, so it turns damp RED litmus BLUE — the opposite of this.",
      ],
      explanation:
        "Gas tests: H₂ — lighted splint, squeaky pop. O₂ — glowing splint relights. CO₂ — limewater turns milky. NH₃ — damp red litmus turns blue. Cl₂ — damp litmus is bleached. The litmus must be damp because the gas has to dissolve in water to act.",
      hints: ["Two of the wrong options have simply swapped hydrogen and oxygen; the other wrong one gets the acid/alkali colour backwards."],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ac-m06",
      topic: "acids",
      section: "acids-tests",
      difficulty: "warmup",
      question: "A compound gives a lilac flame in a flame test. Which metal ion does it contain?",
      options: ["K⁺", "Na⁺", "Li⁺", "Cu²⁺"],
      answerIndex: 0,
      optionFeedback: [
        "Potassium ions give a lilac flame.",
        "Sodium ions give a strong yellow flame, not lilac.",
        "Lithium ions give a red flame.",
        "Copper(II) ions give a blue-green flame.",
      ],
      explanation:
        "Flame test colours: Li⁺ red, Na⁺ yellow, K⁺ lilac, Ca²⁺ orange-red, Cu²⁺ blue-green. A small amount of sodium impurity can mask the lilac colour, which is why the wire must be cleaned first.",
      hints: ["Lilac is a pale purple — it belongs to a Group 1 metal below sodium."],
      strategy: "Recall the definition",
    },
    // ---------------- CORE ----------------
    {
      id: "ac-m07",
      topic: "acids",
      section: "acids-acids",
      difficulty: "core",
      question: "Which is the ionic equation for the neutralisation of nitric acid by potassium hydroxide solution?",
      options: [
        "K⁺(aq) + NO₃⁻(aq) → KNO₃(aq)",
        "HNO₃(aq) + KOH(aq) → KNO₃(aq) + H₂O(l)",
        "H⁺(aq) + OH⁻(aq) → H₂(g) + O₂(g)",
        "H⁺(aq) + OH⁻(aq) → H₂O(l)",
      ],
      answerIndex: 3,
      optionFeedback: [
        "K⁺ and NO₃⁻ are spectator ions — they are dissolved and unchanged before and after, so they are left out of the ionic equation.",
        "This is the full (molecular) balanced equation, not the ionic equation.",
        "Hydrogen ions and hydroxide ions combine to make water, not hydrogen and oxygen gases — and this is not even balanced.",
        "The only change in any acid–alkali neutralisation is H⁺ and OH⁻ combining to form water.",
      ],
      explanation:
        "To write an ionic equation, split everything that is dissolved into ions and cancel the spectator ions that appear on both sides. For any acid + alkali, only H⁺(aq) + OH⁻(aq) → H₂O(l) is left. Remember the state symbols.",
      hints: [
        "An ionic equation leaves out ions that do not change.",
        "Which two ions actually react together to make the water?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "ac-m08",
      topic: "acids",
      section: "acids-acids",
      difficulty: "core",
      question: "Ammonia gas reacts with hydrogen chloride gas: NH₃(g) + HCl(g) → NH₄Cl(s). Which statement describes the role of ammonia in this reaction?",
      options: [
        "It is an acid because it donates a proton.",
        "It is a base because it accepts a proton.",
        "It is a base because it releases OH⁻ ions.",
        "It is an acid because it accepts a proton.",
      ],
      answerIndex: 1,
      optionFeedback: [
        "It is HCl that donates the proton (H⁺) here; ammonia gains it to become NH₄⁺.",
        "NH₃ accepts a proton (H⁺) from HCl to form NH₄⁺, so it acts as a base (proton acceptor).",
        "There is no water and no hydroxide ion anywhere in this reaction — the 'source of OH⁻' definition cannot explain it.",
        "Accepting a proton is what a BASE does; an acid is a proton donor.",
      ],
      explanation:
        "Triple content: an acid is a proton donor and a base is a proton acceptor (a proton is an H⁺ ion). HCl donates H⁺; NH₃ accepts it, forming the ammonium ion NH₄⁺. This wider definition explains acid–base reactions that happen without water.",
      hints: [
        "Compare NH₃ with NH₄⁺ — what has the ammonia gained?",
        "A proton is H⁺. Is ammonia giving one away or taking one?",
      ],
      strategy: "Recall the definition",
    },
    {
      id: "ac-m09",
      topic: "acids",
      section: "acids-acids",
      difficulty: "core",
      question: "Which are the products when zinc carbonate reacts with dilute sulfuric acid?",
      options: [
        "zinc sulfate, water and carbon dioxide",
        "zinc sulfate and hydrogen",
        "zinc oxide, water and sulfur dioxide",
        "zinc sulfate and water only",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Acid + carbonate → salt + water + carbon dioxide; sulfuric acid gives a sulfate.",
        "Salt + hydrogen is the pattern for acid + METAL. A carbonate gives carbon dioxide, not hydrogen.",
        "The zinc ends up in the salt (zinc sulfate), and the gas comes from the carbonate ion, so it is CO₂ not SO₂.",
        "Salt + water only is the pattern for acid + metal oxide or hydroxide. The carbonate ion also releases CO₂ — that is why you see fizzing.",
      ],
      explanation:
        "General reactions of acids: acid + metal → salt + hydrogen; acid + base (oxide/hydroxide) → salt + water; acid + carbonate → salt + water + carbon dioxide. ZnCO₃(s) + H₂SO₄(aq) → ZnSO₄(aq) + H₂O(l) + CO₂(g).",
      hints: [
        "Which general pattern starts 'acid + carbonate → …'?",
        "Which part of the formula ZnCO₃ can become a gas?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "ac-m10",
      topic: "acids",
      section: "acids-acids",
      difficulty: "core",
      question: "Vinegar contains dilute ethanoic acid, a weak acid. Which pH value is most likely for vinegar?",
      options: ["pH 1", "pH 4", "pH 7", "pH 11"],
      answerIndex: 1,
      optionFeedback: [
        "pH 1 is typical of a strong acid such as dilute hydrochloric acid — it contains far more H⁺ ions.",
        "A weak acid releases only some H⁺ ions, so its pH is acidic but not very low — about 3–5.",
        "pH 7 is neutral; ethanoic acid is still an acid, so its pH is below 7.",
        "pH 11 is alkaline — above 7 means more OH⁻ than H⁺ ions.",
      ],
      explanation:
        "The lower the pH, the higher the concentration of H⁺ ions. Universal indicator shows strong acids (pH 0–2) as red and weak acids (pH 3–6) as orange or yellow. At the same concentration a weak acid such as ethanoic acid (vinegar) gives fewer H⁺ ions than a strong acid, so its pH is higher, around 3–4.",
      hints: [
        "Strong acids are pH 0–2. Neutral is 7.",
        "A weak acid is still acidic, but contains fewer H⁺ ions than a strong acid of the same concentration.",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "ac-m11",
      topic: "acids",
      section: "acids-titration",
      difficulty: "core",
      question: "Which burette reading is recorded correctly?",
      options: ["23.4 cm³", "23.47 cm³", "23.45 cm³", "23.453 cm³"],
      answerIndex: 2,
      optionFeedback: [
        "Burette readings must be given to 2 decimal places; '23.4' would need to be written as 23.40 (or 23.45 if the meniscus is half-way).",
        "The second decimal place of a burette reading can only be 0 or 5 — you read to the nearest 0.05 cm³, so 23.47 is not possible.",
        "Burette readings are recorded to 2 decimal places, to the nearest 0.05 cm³.",
        "A burette cannot be read to three decimal places — this claims far more precision than the scale has.",
      ],
      explanation:
        "A burette is graduated every 0.10 cm³, and you can judge whether the meniscus is on a line or half-way between, so readings are recorded to the nearest 0.05 cm³: the last digit is always 0 or 5. Read the bottom of the meniscus with your eye level with it. Q5(b)(i) on your teacher's paper tests exactly this.",
      hints: [
        "How many decimal places should every burette reading have?",
        "The smallest step you can judge is half a 0.10 cm³ division.",
      ],
      strategy: "Check the units",
    },
    {
      id: "ac-m12",
      topic: "acids",
      section: "acids-titration",
      difficulty: "core",
      question: "Concordant results are within 0.20 cm³ of each other. What is the mean titre that should be reported?",
      table: {
        headers: ["", "Rough", "Titration 1", "Titration 2", "Titration 3"],
        rows: [["Titre (cm³)", "25.10", "24.45", "24.20", "24.10"]],
      },
      options: ["24.15 cm³", "24.25 cm³", "24.46 cm³", "24.20 cm³"],
      answerIndex: 0,
      optionFeedback: [
        "Only titrations 2 and 3 are concordant (0.10 cm³ apart): (24.20 + 24.10) ÷ 2 = 24.15 cm³.",
        "This is the mean of all three accurate titres, but titration 1 is 0.25 cm³ away from titration 2 — it is not concordant and must be left out.",
        "This is the mean of all four titres including the rough. The rough titration is never included in the mean.",
        "This is just one of the titres (titration 2), not a mean.",
      ],
      explanation:
        "Step 1: ignore the rough titration — the acid was added quickly to find the approximate end point.\nStep 2: find titres within 0.20 cm³ of each other: 24.20 and 24.10 (difference 0.10 cm³). 24.45 differs from both by more than 0.20 cm³.\nStep 3: mean = (24.20 + 24.10) ÷ 2 = 24.15 cm³.",
      hints: [
        "Which titre is never included in the mean?",
        "Of the accurate titres, which ones agree with each other within 0.20 cm³?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "ac-m13",
      topic: "acids",
      section: "acids-titration",
      difficulty: "core",
      question: "Why is a burette rinsed with the acid it will contain, rather than with distilled water, just before a titration?",
      options: [
        "To make the acid flow out of the tap faster",
        "To remove air bubbles from inside the tap",
        "To warm the burette to room temperature",
        "So that the acid is not diluted by water left inside",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Rinsing does not change the flow rate — that is controlled by the tap.",
        "Air bubbles in the jet are removed by running some acid through the tap after filling, not by rinsing.",
        "Rinsing with the acid has nothing to do with temperature.",
        "Drops of water left in the burette would dilute the acid, lowering its concentration and making the titre too large.",
      ],
      explanation:
        "Any water left from washing would dilute the acid, so a larger volume would be needed to neutralise the alkali — a systematic error. Likewise, rinse the pipette with the alkali. The conical flask, however, may be rinsed with distilled water: water in the flask does not change the number of moles of alkali pipetted in.",
      hints: [
        "What would a few drops of water do to the concentration of the acid?",
        "If the acid is weaker, would you need more or less of it to reach the end point?",
      ],
      strategy: "Follow the method step by step",
    },
    {
      id: "ac-m14",
      topic: "acids",
      section: "acids-titration",
      difficulty: "core",
      question: "25.0 cm³ of 0.100 mol/dm³ sodium hydroxide is neutralised by 20.00 cm³ of hydrochloric acid. NaOH + HCl → NaCl + H₂O. What is the concentration of the hydrochloric acid?",
      options: ["0.0800 mol/dm³", "0.00250 mol/dm³", "0.125 mol/dm³", "0.0625 mol/dm³"],
      answerIndex: 2,
      optionFeedback: [
        "This comes from dividing the wrong way round (0.100 × 20.00 ÷ 25.0). The acid volume is smaller, so the acid must be MORE concentrated than the alkali.",
        "This is the number of moles of NaOH (and HCl), not the concentration — you still need to divide by the acid volume in dm³.",
        "moles NaOH = 0.0025 mol = moles HCl; 0.0025 ÷ 0.0200 dm³ = 0.125 mol/dm³.",
        "This is what you get if you use a 1 : 2 ratio. The equation shows NaOH and HCl react 1 : 1.",
      ],
      explanation:
        "moles NaOH = 0.100 × 25.0/1000 = 0.00250 mol\nRatio 1 : 1, so moles HCl = 0.00250 mol\nconcentration HCl = 0.00250 ÷ (20.00/1000) = 0.125 mol/dm³\nCheck: less acid than alkali was needed, so the acid is more concentrated — sensible.",
      hints: [
        "First work out the moles of sodium hydroxide: concentration × volume in dm³.",
        "Use the 1 : 1 ratio, then divide by the acid volume in dm³.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "ac-m15",
      topic: "acids",
      section: "acids-salts",
      difficulty: "core",
      question: "When making copper(II) sulfate crystals, copper(II) oxide is added to warm dilute sulfuric acid until some black solid remains. Why is the copper(II) oxide added in excess?",
      options: [
        "To make the crystals form more quickly",
        "To make sure all of the acid has reacted",
        "To act as a catalyst for the reaction",
        "To turn the solution a darker blue colour",
      ],
      answerIndex: 1,
      optionFeedback: [
        "The excess solid has no effect on how fast crystals form later — that depends on evaporation and cooling.",
        "With the oxide in excess, all of the sulfuric acid is used up, so no acid contaminates the salt; the leftover solid is simply filtered off.",
        "Copper(II) oxide is a reactant, not a catalyst — it is used up as it reacts.",
        "The colour comes from the Cu²⁺ ions formed; extra undissolved oxide does not make the solution any darker.",
      ],
      explanation:
        "Adding the insoluble base until it is in excess guarantees that no acid is left in the solution. Because copper(II) oxide is insoluble, the excess can then be removed easily by filtration. Your teacher's Q1(a) asks why the mixture is filtered: to remove the excess (unreacted) solid.",
      hints: [
        "Which reactant would contaminate the final salt solution if any of it were left over?",
        "The excess solid is easy to remove — what about leftover acid?",
      ],
      strategy: "Follow the method step by step",
    },
    {
      id: "ac-m16",
      topic: "acids",
      section: "acids-salts",
      difficulty: "core",
      question: "Which pair of substances is most suitable for making a pure sample of lead(II) sulfate?",
      options: [
        "lead metal and dilute sulfuric acid",
        "lead(II) carbonate and dilute sulfuric acid",
        "lead(II) chloride and sodium sulfate solution",
        "lead(II) nitrate solution and sodium sulfate solution",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Lead reacts only very slowly with dilute sulfuric acid, and any insoluble lead(II) sulfate formed coats the metal and stops the reaction.",
        "Insoluble lead(II) sulfate forms a coating on the carbonate and the reaction soon stops; the product would be mixed with unreacted carbonate.",
        "Lead(II) chloride is insoluble, so it cannot provide Pb²⁺ ions in solution to react.",
        "Both are soluble, so mixing them precipitates insoluble lead(II) sulfate, which is filtered, washed and dried.",
      ],
      explanation:
        "Insoluble salts are made by precipitation: mix a solution containing the cation with a solution containing the anion. Nitrates are always soluble, so lead(II) nitrate supplies Pb²⁺; sodium sulfate supplies SO₄²⁻. Pb²⁺(aq) + SO₄²⁻(aq) → PbSO₄(s). Then filter, wash with distilled water and dry.",
      hints: [
        "Is lead(II) sulfate soluble or insoluble? That decides the method.",
        "For precipitation, both starting substances must be soluble.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ac-m17",
      topic: "acids",
      section: "acids-salts",
      difficulty: "core",
      question: "Why is a solution of copper(II) sulfate heated only to its crystallisation point and not to dryness?",
      options: [
        "Heating to dryness would remove the water of crystallisation",
        "Copper(II) sulfate is a very flammable compound",
        "The crystals would react with the evaporating basin",
        "Heating to dryness would make the solution acidic again",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Blue hydrated crystals, CuSO₄·5H₂O, contain water of crystallisation; strong heating drives it off, leaving white anhydrous copper(II) sulfate.",
        "Copper(II) sulfate is not flammable — this has nothing to do with the reason.",
        "Copper(II) sulfate does not react with a porcelain evaporating basin.",
        "Evaporating water does not create acid; the acid has already been used up by the excess copper(II) oxide.",
      ],
      explanation:
        "Hydrated salts lose their water of crystallisation if heated to dryness — you would get a white powder instead of blue crystals. Some salts, such as sodium nitrate (teacher's Q5c), decompose when heated strongly. Crystallising slowly also leaves soluble impurities behind in the solution.",
      hints: [
        "What does the '·5H₂O' in CuSO₄·5H₂O stand for?",
        "What happens to blue copper(II) sulfate crystals when they are heated strongly?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "ac-m18",
      topic: "acids",
      section: "acids-tests",
      difficulty: "core",
      question: "Which reagents are used to test a solution for sulfate ions?",
      options: [
        "dilute sulfuric acid, then barium chloride solution",
        "dilute nitric acid, then silver nitrate solution",
        "dilute hydrochloric acid, then barium chloride solution",
        "sodium hydroxide solution, then warm gently",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Sulfuric acid adds sulfate ions itself, so you would always get a white precipitate — a false positive.",
        "This is the test for halide ions (chloride, bromide, iodide), not sulfate.",
        "Dilute HCl removes carbonate ions; then barium chloride gives a white precipitate of barium sulfate if sulfate is present.",
        "Sodium hydroxide tests for metal cations and, on warming, for ammonium ions — not for anions like sulfate.",
      ],
      explanation:
        "Sulfate test: add dilute hydrochloric acid, then barium chloride solution; a white precipitate of BaSO₄ shows sulfate ions. The acid is added first to remove carbonate ions, which would also form a white precipitate (barium carbonate). Never use the acid containing the ion you are testing for.",
      hints: [
        "The precipitate formed is barium sulfate.",
        "Which acid would add sulfate ions and ruin the test?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "ac-m19",
      topic: "acids",
      section: "acids-tests",
      difficulty: "core",
      question: "Sodium hydroxide solution is added to a solution of a salt. A green precipitate forms. Which ion is present?",
      options: ["Fe³⁺", "Fe²⁺", "Cu²⁺", "NH₄⁺"],
      answerIndex: 1,
      optionFeedback: [
        "Iron(III) ions give a brown (orange-brown) precipitate of Fe(OH)₃.",
        "Iron(II) ions give a green precipitate of iron(II) hydroxide, Fe(OH)₂.",
        "Copper(II) ions give a blue precipitate of Cu(OH)₂.",
        "Ammonium ions give no precipitate; on warming they release ammonia gas.",
      ],
      explanation:
        "NaOH(aq) test: Cu²⁺ blue precipitate; Fe²⁺ green precipitate; Fe³⁺ brown precipitate; NH₄⁺ no precipitate but ammonia on warming (turns damp red litmus blue). Fe²⁺(aq) + 2OH⁻(aq) → Fe(OH)₂(s).",
      hints: [
        "Iron(II) and iron(III) hydroxides are different colours.",
        "Copper(II) hydroxide is blue — which iron hydroxide is green?",
      ],
      strategy: "Recall the definition",
    },
    // ---------------- CHALLENGE ----------------
    {
      id: "ac-m20",
      topic: "acids",
      section: "acids-titration",
      difficulty: "challenge",
      question: "22.40 cm³ of 0.0500 mol/dm³ sulfuric acid exactly neutralises 25.0 cm³ of sodium hydroxide solution. H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. What is the concentration of the sodium hydroxide?",
      options: ["0.0448 mol/dm³", "0.0558 mol/dm³", "0.00224 mol/dm³", "0.0896 mol/dm³"],
      answerIndex: 3,
      optionFeedback: [
        "This is what you get if you forget the 1 : 2 mole ratio — each H₂SO₄ neutralises TWO NaOH.",
        "This comes from swapping the volumes (0.0500 × 25.0 ÷ 22.40) and ignoring the ratio.",
        "This is the number of moles of NaOH, not its concentration — divide by 0.0250 dm³.",
        "moles H₂SO₄ = 0.001120; moles NaOH = 2 × 0.001120 = 0.002240; ÷ 0.0250 dm³ = 0.0896 mol/dm³.",
      ],
      explanation:
        "moles H₂SO₄ = 0.0500 × 22.40/1000 = 0.001120 mol\nmole ratio H₂SO₄ : NaOH = 1 : 2, so moles NaOH = 0.002240 mol\nconcentration NaOH = 0.002240 ÷ (25.0/1000) = 0.0896 mol/dm³\nSulfuric acid is diprotic: each molecule releases two H⁺ ions, so it neutralises twice as much alkali.",
      hints: [
        "Start with the substance whose concentration AND volume you know.",
        "Look at the equation: how many NaOH react with one H₂SO₄?",
        "Convert 25.0 cm³ to dm³ before dividing.",
      ],
      strategy: "Use the mole ratio",
    },
    {
      id: "ac-m21",
      topic: "acids",
      section: "acids-tests",
      difficulty: "challenge",
      question: "A white solid X dissolves in water. Adding sodium hydroxide solution gives no precipitate, but on warming a gas is given off that turns damp red litmus blue. Adding dilute hydrochloric acid to X causes no fizzing, but then adding barium chloride solution gives a white precipitate. What is X?",
      options: ["ammonium sulfate", "ammonium chloride", "ammonium carbonate", "sodium sulfate"],
      answerIndex: 0,
      optionFeedback: [
        "NH₄⁺ (ammonia released on warming with NaOH) and SO₄²⁻ (white precipitate with acidified BaCl₂) — ammonium sulfate.",
        "Ammonium chloride fits the ammonia result, but chloride gives no precipitate with barium chloride — chlorides of barium are soluble.",
        "A carbonate would fizz when dilute hydrochloric acid is added — the question says there is no fizzing.",
        "Sodium sulfate fits the barium chloride test, but sodium ions would not release ammonia when warmed with NaOH.",
      ],
      explanation:
        "Combine one cation result and one anion result. Ammonia gas (damp red litmus → blue) on warming with NaOH(aq) proves NH₄⁺: NH₄⁺ + OH⁻ → NH₃ + H₂O. No fizz with acid rules out carbonate; white precipitate with HCl then BaCl₂ proves SO₄²⁻. X = (NH₄)₂SO₄, a common fertiliser.",
      hints: [
        "Which ion releases a gas that turns damp red litmus blue when warmed with alkali?",
        "Which anion does acidified barium chloride detect?",
        "What would you have seen if X were a carbonate?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "ac-m22",
      topic: "acids",
      section: "acids-tests",
      difficulty: "challenge",
      question: "A student tests a solution for chloride ions by adding dilute hydrochloric acid and then silver nitrate solution. She sees a white precipitate. Why is her conclusion that the solution contains chloride ions not valid?",
      options: [
        "Hydrochloric acid reacts with silver nitrate to give off chlorine gas",
        "Silver chloride is soluble in hydrochloric acid, so no result is possible",
        "The acid itself adds chloride ions, so a white precipitate forms anyway",
        "Hydrochloric acid removes the chloride ions as hydrogen chloride gas",
      ],
      answerIndex: 2,
      optionFeedback: [
        "No chlorine gas is formed; Ag⁺ and Cl⁻ simply combine to make a silver chloride precipitate.",
        "Silver chloride is insoluble in dilute acids — that is exactly why it precipitates.",
        "HCl contains Cl⁻ ions, which react with Ag⁺ to form white AgCl whether or not the sample had chloride — a false positive.",
        "Dilute hydrochloric acid does not remove chloride ions; it adds them.",
      ],
      explanation:
        "In the halide test the acid is added to remove carbonate ions (which would also give a precipitate with silver ions). The acid must not contain the ion being tested for, so dilute NITRIC acid is used. Similarly, the sulfate test uses hydrochloric acid, not sulfuric acid. This is the skill in your teacher's Q2(b)(ii).",
      hints: [
        "Write out the ions present in hydrochloric acid.",
        "What would Ag⁺ ions do with those ions, even in pure water?",
        "Which acid is normally used in the halide test, and why that one?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "ac-m23",
      topic: "acids",
      section: "acids-salts",
      difficulty: "challenge",
      question: "Which salt would have to be prepared by the titration method rather than by adding an excess of a solid to a dilute acid and filtering?",
      options: ["magnesium sulfate", "zinc chloride", "copper(II) nitrate", "potassium nitrate"],
      answerIndex: 3,
      optionFeedback: [
        "Magnesium sulfate can be made from excess insoluble magnesium oxide, magnesium carbonate or magnesium metal with sulfuric acid, then filtering.",
        "Zinc chloride can be made by adding excess zinc, zinc oxide or zinc carbonate to hydrochloric acid and filtering.",
        "Copper(II) nitrate can be made from excess copper(II) oxide or carbonate with nitric acid, then filtering.",
        "Potassium compounds that react with acid (KOH, K₂CO₃) are soluble and potassium metal is far too reactive, so the excess could not be filtered off — titration with KOH is needed.",
      ],
      explanation:
        "The excess method only works if the excess reactant is an insoluble solid that can be filtered off. Sodium, potassium and ammonium hydroxides and carbonates are all soluble, and sodium and potassium metals react dangerously with acids. So their salts are made by titration: find the exact volumes with an indicator, repeat without the indicator, then crystallise.",
      hints: [
        "The excess method needs a reactant that is insoluble so it can be filtered off.",
        "Which metal's hydroxide and carbonate are both soluble in water?",
        "Could you safely drop the metal itself into acid?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "ac-m24",
      topic: "acids",
      section: "acids-titration",
      difficulty: "challenge",
      question: "At the start of a titration there is an air bubble in the jet below the burette tap. During the titration the bubble is pushed out and replaced by acid. What effect does this have on the recorded titre?",
      options: [
        "The titre is too small, because the bubble blocks the flow",
        "The titre is too large, because the bubble's volume is counted as acid added",
        "There is no effect, because the bubble is below the scale",
        "There is no effect, because concordant results cancel it out",
      ],
      answerIndex: 1,
      optionFeedback: [
        "The bubble does not block the flow; the error comes from the scale reading, not the flow rate.",
        "The level in the burette falls by the bubble's volume as acid fills the jet, but that acid never reaches the flask — so the recorded titre is larger than the volume actually added.",
        "Exactly because the jet is below the scale, acid filling it still lowers the level you read — so the reading changes.",
        "Concordance shows results agree with each other; a mistake made in one titration is not cancelled out by the others.",
      ],
      explanation:
        "Recorded titre = final reading − initial reading. When the bubble is replaced by acid, the meniscus falls by the bubble's volume, but that acid stays in the jet instead of reacting in the flask. The recorded volume is therefore larger than the true volume needed. Prevention: after filling, run some acid through the tap to fill the jet before taking the initial reading.",
      hints: [
        "When acid fills the space the bubble left, where does that acid come from?",
        "Does that acid reach the conical flask?",
        "So is the drop in the burette reading bigger or smaller than the volume added to the flask?",
      ],
      strategy: "Think about particles",
    },
  ],
};
